### ISSUE TITLE
Icon cannot be found in '/icons/nodes/plugin.png', aClass='class com.mallowigi.icons.FileIconProvider'

### ISSUE THREAD

**Issue by CombeeMike** [mallowigi/a-file-icon-idea#1]
Hi,

PhpStorm periodically reports the following error:

> Icon cannot be found in '/icons/nodes/plugin.png', aClass='class com.mallowigi.icons.FileIconProvider'

Whilst this doesn't prevent the plugin from working (I didn't even notice any missing icons so far), the constant popup of the IDEA error notification is a little annoying.

Details:

![error](https://user-images.githubusercontent.com/30658772/36893655-232ac284-1e09-11e8-991f-1926546e56ad.png)

```
Icon cannot be found in '/icons/nodes/plugin.png', aClass='class com.mallowigi.icons.FileIconProvider'
java.lang.Throwable: Icon cannot be found in '/icons/nodes/plugin.png', aClass='class com.mallowigi.icons.FileIconProvider'
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:136)
	at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:157)
	at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:118)
	at com.mallowigi.icons.FileIconProvider.loadIcon(FileIconProvider.java:158)
	at com.mallowigi.icons.FileIconProvider.getIconForAssociation(FileIconProvider.java:141)
	at com.mallowigi.icons.FileIconProvider.getIcon(FileIconProvider.java:73)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:42)
	at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:118)
	at com.intellij.psi.impl.ElementBase.lambda$static$0(ElementBase.java:59)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:278)
	at com.intellij.ui.DeferredIconImpl.b(DeferredIconImpl.java:163)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:111)
	at com.intellij.ui.DeferredIconImpl.a(DeferredIconImpl.java:163)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1127)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:85)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:141)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:139)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:85)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:106)
	at com.intellij.ui.DeferredIconImpl.a(DeferredIconImpl.java:162)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


java.lang.Throwable: Icon cannot be found in '/icons/nodes/plugin.png', aClass='class com.mallowigi.icons.FileIconProvider'
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:136)
	at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:157)
	at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:118)
	at com.mallowigi.icons.FileIconProvider.loadIcon(FileIconProvider.java:158)
	at com.mallowigi.icons.FileIconProvider.getIconForAssociation(FileIconProvider.java:141)
	at com.mallowigi.icons.FileIconProvider.getIcon(FileIconProvider.java:73)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:42)
	at com.intellij.ide.FileIconPatcherImpl.getIcon(FileIconPatcherImpl.java:40)
	at com.intellij.util.IconUtil.getProvidersIcon(IconUtil.java:197)
	at com.intellij.util.IconUtil.lambda$static$0(IconUtil.java:152)
	at com.intellij.ui.IconDeferrerImpl.a(IconDeferrerImpl.java:78)
	at com.intellij.ui.IconDeferrerImpl.defer(IconDeferrerImpl.java:68)
	at com.intellij.util.IconUtil.getIcon(IconUtil.java:191)
	at com.intellij.psi.impl.ElementBase.getElementIcon(ElementBase.java:229)
	at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:122)
	at com.intellij.psi.impl.ElementBase.lambda$static$0(ElementBase.java:59)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:278)
	at com.intellij.ui.DeferredIconImpl.b(DeferredIconImpl.java:163)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:111)
	at com.intellij.ui.DeferredIconImpl.a(DeferredIconImpl.java:163)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1127)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:85)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:141)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:139)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:85)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:106)
	at com.intellij.ui.DeferredIconImpl.a(DeferredIconImpl.java:162)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


java.lang.Throwable: Icon cannot be found in '/icons/nodes/plugin.png', aClass='class com.mallowigi.icons.FileIconProvider'
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:136)
	at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:157)
	at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:118)
	at com.mallowigi.icons.FileIconProvider.loadIcon(FileIconProvider.java:158)
	at com.mallowigi.icons.FileIconProvider.getIconForAssociation(FileIconProvider.java:141)
	at com.mallowigi.icons.FileIconProvider.getIcon(FileIconProvider.java:73)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:42)
	at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:118)
	at com.intellij.psi.impl.ElementBase.lambda$static$0(ElementBase.java:59)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:278)
	at com.intellij.ui.DeferredIconImpl.b(DeferredIconImpl.java:163)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:111)
	at com.intellij.ui.DeferredIconImpl.a(DeferredIconImpl.java:163)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1127)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:85)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:141)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:139)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:85)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:106)
	at com.intellij.ui.DeferredIconImpl.a(DeferredIconImpl.java:162)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


java.lang.Throwable: Icon cannot be found in '/icons/nodes/plugin.png', aClass='class com.mallowigi.icons.FileIconProvider'
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:136)
	at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:157)
	at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:118)
	at com.mallowigi.icons.FileIconProvider.loadIcon(FileIconProvider.java:158)
	at com.mallowigi.icons.FileIconProvider.getIconForAssociation(FileIconProvider.java:141)
	at com.mallowigi.icons.FileIconProvider.getIcon(FileIconProvider.java:73)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:42)
	at com.intellij.ide.FileIconPatcherImpl.getIcon(FileIconPatcherImpl.java:40)
	at com.intellij.util.IconUtil.getProvidersIcon(IconUtil.java:197)
	at com.intellij.util.IconUtil.lambda$static$0(IconUtil.java:152)
	at com.intellij.ui.IconDeferrerImpl.a(IconDeferrerImpl.java:78)
	at com.intellij.ui.IconDeferrerImpl.defer(IconDeferrerImpl.java:68)
	at com.intellij.util.IconUtil.getIcon(IconUtil.java:191)
	at com.intellij.psi.impl.ElementBase.getElementIcon(ElementBase.java:229)
	at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:122)
	at com.intellij.psi.impl.ElementBase.lambda$static$0(ElementBase.java:59)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:278)
	at com.intellij.ui.DeferredIconImpl.b(DeferredIconImpl.java:163)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:111)
	at com.intellij.ui.DeferredIconImpl.a(DeferredIconImpl.java:163)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1127)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:85)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:141)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:139)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:85)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:106)
	at com.intellij.ui.DeferredIconImpl.a(DeferredIconImpl.java:162)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


java.lang.Throwable: Icon cannot be found in '/icons/nodes/plugin.png', aClass='class com.mallowigi.icons.FileIconProvider'
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:136)
	at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:157)
	at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:118)
	at com.mallowigi.icons.FileIconProvider.loadIcon(FileIconProvider.java:158)
	at com.mallowigi.icons.FileIconProvider.getIconForAssociation(FileIconProvider.java:141)
	at com.mallowigi.icons.FileIconProvider.getIcon(FileIconProvider.java:73)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:42)
	at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:118)
	at com.intellij.psi.impl.ElementBase.lambda$static$0(ElementBase.java:59)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:278)
	at com.intellij.ui.DeferredIconImpl.b(DeferredIconImpl.java:163)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:111)
	at com.intellij.ui.DeferredIconImpl.a(DeferredIconImpl.java:163)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1127)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:85)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:141)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:139)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:85)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:106)
	at com.intellij.ui.DeferredIconImpl.a(DeferredIconImpl.java:162)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


java.lang.Throwable: Icon cannot be found in '/icons/nodes/plugin.png', aClass='class com.mallowigi.icons.FileIconProvider'
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:136)
	at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:157)
	at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:118)
	at com.mallowigi.icons.FileIconProvider.loadIcon(FileIconProvider.java:158)
	at com.mallowigi.icons.FileIconProvider.getIconForAssociation(FileIconProvider.java:141)
	at com.mallowigi.icons.FileIconProvider.getIcon(FileIconProvider.java:73)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:42)
	at com.intellij.ide.FileIconPatcherImpl.getIcon(FileIconPatcherImpl.java:40)
	at com.intellij.util.IconUtil.getProvidersIcon(IconUtil.java:197)
	at com.intellij.util.IconUtil.lambda$static$0(IconUtil.java:152)
	at com.intellij.ui.IconDeferrerImpl.a(IconDeferrerImpl.java:78)
	at com.intellij.ui.IconDeferrerImpl.defer(IconDeferrerImpl.java:68)
	at com.intellij.util.IconUtil.getIcon(IconUtil.java:191)
	at com.intellij.psi.impl.ElementBase.getElementIcon(ElementBase.java:229)
	at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:122)
	at com.intellij.psi.impl.ElementBase.lambda$static$0(ElementBase.java:59)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:278)
	at com.intellij.ui.DeferredIconImpl.b(DeferredIconImpl.java:163)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:111)
	at com.intellij.ui.DeferredIconImpl.a(DeferredIconImpl.java:163)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1127)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:85)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:141)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:139)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:85)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:106)
	at com.intellij.ui.DeferredIconImpl.a(DeferredIconImpl.java:162)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mallowigi** [comment]
Eap version?

**Comment by mallowigi** [comment]
I’m fixing this in the next version. I haven’t updated the plugin in a while
