### ISSUE TITLE
Turning off UI icons breaks many file type icons

### ISSUE THREAD

**Issue by ihorvorotnov** [mallowigi/a-file-icon-idea#17]
There are couple issues with UI icons settings.

First of all, to enable  them, you must select *both* "enable monochrome icons and UI icons, then "Apply" button activates, and after restart UI icons are applied. However, they are not monochrome.

After enabling, it's not that easy to disable them back. Turning both checkboxes off activates "Apply" button, but the new settings aren't applied (button isn't clickable). However, clicking "Ok" applies the changes. 

But after disabling both monochrome and UI icons, many file type icons are broken (reverted to standard, see PHP files on screenshot below for example):

<img width="358" alt="screen shot 2018-12-10 at 13 29 04" src="https://user-images.githubusercontent.com/1066083/49730236-6aa4d180-fc80-11e8-8c05-ff54edfa11a4.png">

This is how they look with UI icons turned on:

<img width="367" alt="screen shot 2018-12-10 at 13 14 22" src="https://user-images.githubusercontent.com/1066083/49730260-7d1f0b00-fc80-11e8-9b74-f1dedcb2d94e.png">

Turning on / off only a single checkbox for UI icons does not work at all. "Apply" button isn't activated, clicking "Ok" does not apply the setting.

Sometimes right after applying "Monochrome" option but before the restart UI gets broken even worse:

<img width="1072" alt="screen shot 2018-12-10 at 13 39 13" src="https://user-images.githubusercontent.com/1066083/49730434-03d3e800-fc81-11e8-92ac-f7671863f5da.png">

This happens on latest PhpStorm 2018.3.1 + plugin 8.1

**Comment by mallowigi** [comment]
Just for information, UI Icons option still needs a full restart to apply. I’m working on that though.

Monochrome icons should cover the whole Ui With a black and white filter, but I’m concerned about your issue though. It looks like it’s trying to color in black everything, not only icons. I’ll check that out.

**Comment by ihorvorotnov** [comment]
> Just for information, UI Icons option still needs a full restart to apply. I’m working on that though.

Yup, doing full restart after each change.

**Comment by mallowigi** [comment]
By the way from your screenshot the behavior of monochrome icons look fine... except that it should be white instead of black for dark themes.

**Comment by ihorvorotnov** [comment]
Yes, it should be white. Also, the filter shouldn't be applied to the entire app window. Also, please note the PHP file icons, they aren't "elephants" anymore (happens when turning off UI icons).

Additional note - even if UI icons are turned on with color option, when the "Welcome" pane loads (where you select your project) there's a flash of monochrome icons first (black on dark background), then they are changed to colored icons.

**Comment by mallowigi** [comment]
[Atom File Icons IDEA-8.1.zip](https://github.com/mallowigi/a-file-icon-idea/files/2673918/Atom.File.Icons.IDEA-8.1.zip)

Hey,

I have a favor to ask, since I'm a little short handed at the moment to be able to do proper QA, can you help me in this task? I've uploaded the file with the latest changes.

In these changes, I've fixed most of the issues: 
- monochrome color is now selectable
- UI Icons apply without restart 
- the PHP icon is now dependent on the File icons option
- Monochrome icons option is persisted at start
- The arrows in the tree are now painted in Gray (hardcoded for now)

Thanks

**Comment by ihorvorotnov** [comment]
@mallowigi Sure, I'm installing it right now and will be testing during the day. Thanks for quick update!

**Comment by ihorvorotnov** [comment]
Setting custom monochrome tint is nice, looks great with custom themes:

<img width="474" alt="screen shot 2018-12-13 at 11 06 19" src="https://user-images.githubusercontent.com/1066083/49927719-4555d480-fec7-11e8-8c72-62fa2cb45246.png"> 
<img width="352" alt="screen shot 2018-12-13 at 11 08 28" src="https://user-images.githubusercontent.com/1066083/49927790-76360980-fec7-11e8-9d9d-3a8f8a588eb0.png">

But there are some issues. First, at start there's an error:

```
java.lang.Throwable: Assertion failed: Write access is allowed inside write-action only (see com.intellij.openapi.application.Application.runWriteAction())
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertWriteAccessAllowed(ApplicationImpl.java:1346)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.fireRootsChanged(ProjectRootManagerImpl.java:369)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.access$200(ProjectRootManagerImpl.java:38)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl$BatchSession.rootsChanged(ProjectRootManagerImpl.java:98)
	at com.intellij.openapi.roots.impl.ProjectRootManagerComponent.rootsChanged(ProjectRootManagerComponent.java:137)
	at com.intellij.openapi.roots.impl.ProjectRootManagerComponent.access$100(ProjectRootManagerComponent.java:52)
	at com.intellij.openapi.roots.impl.ProjectRootManagerComponent$1.fileTypesChanged(ProjectRootManagerComponent.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:397)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:358)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:347)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:324)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:29)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:196)
	at com.sun.proxy.$Proxy77.fileTypesChanged(Unknown Source)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.fireFileTypesChanged(FileTypeManagerImpl.java:1014)
	at com.mallowigi.icons.IconReplacerComponent.updateFileIcons(IconReplacerComponent.java:123)
	at com.mallowigi.icons.IconReplacerComponent.onSettingsChanged(IconReplacerComponent.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:397)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:358)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:347)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:324)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:29)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:196)
	at com.sun.proxy.$Proxy76.configChanged(Unknown Source)
	at com.mallowigi.config.AtomFileIconsConfig.fireChanged(AtomFileIconsConfig.java:96)
	at com.mallowigi.config.AtomFileIconsConfig.applySettings(AtomFileIconsConfig.java:106)
	at com.mallowigi.config.Configurable.doApply(Configurable.java:72)
	at com.mallowigi.config.Configurable.doApply(Configurable.java:38)
	at com.mallowigi.config.ConfigurableBase.apply(ConfigurableBase.java:109)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.apply(ConfigurableWrapper.java:173)
	at com.intellij.openapi.options.newEditor.ConfigurableEditor.apply(ConfigurableEditor.java:316)
	at com.intellij.openapi.options.newEditor.SettingsEditor$5.apply(SettingsEditor.java:163)
	at com.intellij.openapi.options.newEditor.ConfigurableEditor$2.actionPerformed(ConfigurableEditor.java:65)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6548)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6313)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4903)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:664)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.awt.Dialog.show(Dialog.java:1077)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:698)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:430)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1681)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1630)
	at com.intellij.openapi.options.newEditor.SettingsDialog.lambda$show$0(SettingsDialog.java:70)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:153)
	at com.intellij.openapi.options.newEditor.SettingsDialog.show(SettingsDialog.java:70)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:84)
	at com.intellij.ide.actions.ShowSettingsAction.perform(ShowSettingsAction.java:50)
	at com.intellij.ide.actions.ShowSettingsAction.actionPerformed(ShowSettingsAction.java:39)
	at com.intellij.openapi.wm.impl.welcomeScreen.FlatWelcomeFrame$FlatWelcomeScreen$IconsFreeActionGroup$1.actionPerformed(FlatWelcomeFrame.java:776)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:258)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:275)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:249)
	at com.intellij.ui.popup.ActionPopupStep.performAction(ActionPopupStep.java:200)
	at com.intellij.ui.popup.ActionPopupStep.performAction(ActionPopupStep.java:190)
	at com.intellij.ui.popup.ActionPopupStep.lambda$onChosen$2(ActionPopupStep.java:184)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.ui.popup.AbstractPopup.lambda$dispose$12(AbstractPopup.java:1399)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:3048)
	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:172)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:124)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:179)
	at com.intellij.ui.popup.AbstractPopup.dispose(AbstractPopup.java:1395)
	at com.intellij.ui.popup.WizardPopup.dispose(WizardPopup.java:160)
	at com.intellij.ui.popup.list.ListPopupImpl.dispose(ListPopupImpl.java:308)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.dispose(PopupFactoryImpl.java:279)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:48)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:44)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:138)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:107)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:182)
	at com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:107)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeAll(ObjectTree.java:151)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:129)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:125)
	at com.intellij.ui.popup.WizardPopup.disposeAllParents(WizardPopup.java:263)
	at com.intellij.ui.popup.list.ListPopupImpl.handleNextStep(ListPopupImpl.java:444)
	at com.intellij.ui.popup.list.ListPopupImpl._handleSelect(ListPopupImpl.java:397)
	at com.intellij.ui.popup.list.ListPopupImpl.handleSelect(ListPopupImpl.java:343)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.handleSelect(PopupFactoryImpl.java:299)
	at com.intellij.ui.popup.list.ListPopupImpl$MyMouseListener.mouseReleased(ListPopupImpl.java:503)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.Component.processMouseEvent(Component.java:6548)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at com.intellij.ui.popup.list.ListPopupImpl$MyList.processMouseEvent(ListPopupImpl.java:557)
	at java.awt.Component.processEvent(Component.java:6313)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4903)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:664)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by ihorvorotnov** [comment]
Second, there's still inconsistency in icon states and corresponding settings checked. Let's go one by one:

1. All 4 checkboxes turned off (unchecked).

- Welcome screen looks ok
- Settings screen looks ok
- Main app screen looks ok
- No exception thrown on startup

2. "Enable File Icons" is checked.

- **Exception is thrown** immediately after activating (or deactivating) this option (see prev comment). If PhpStorm is restarted, there' no exception.
- File icons are applied immediately
- Welcome screen is ok
- Settings screen is ok
- Main app screen is ok

3. Additionally to 2, "Enable Directory Icons" is checked

- **Same exception** (on activation, deactivation, no exception after restart)
- Directory icons are applied immediately
- Welcome screen is ok
- Settings screen is ok
- Main app screen is ok

4. Additionally, "Enable UI Icons" is checked, "Monochrome" options is still off

- **Same exception**
- UI icons are applied immediately
- Welcome screen looks ok
- Settings screen looks ok
- **Main app screen has issues** - some native PhpStorm's UI icons (which aren't replaced by the plugin), like "read-only" lock in status bar have monochrome tint (546E7A) applied, although the "monochrome" checkbox is unchecked

<img width="260" alt="screen shot 2018-12-13 at 11 27 50" src="https://user-images.githubusercontent.com/1066083/49929104-548a5180-feca-11e8-98a2-211d15be3e5b.png">

Those icons should keep their default colors.

5. "Monochrome Icons" is checked.

- **Same exception**
- Tint is applied immediately, with a flash (some UI elements become hardly noticeable due to low contrast, see screenshots below, checkboxes in settings become much darker)
- Welcome screen looks ok
- All other screens have minor issues, mostly low color contrast of elements:

Hector isn't visible at all:

<img width="276" alt="screen shot 2018-12-13 at 11 35 44" src="https://user-images.githubusercontent.com/1066083/49929495-4a1c8780-fecb-11e8-8939-3b8cf4b9fda2.png">

Search icon is hardly noticeable, all checkboxes are dark (although that's probably fine):

<img width="994" alt="screen shot 2018-12-13 at 11 36 52" src="https://user-images.githubusercontent.com/1066083/49929554-71735480-fecb-11e8-9c01-79fceb24dcb0.png">

Inactive icons in settings UI are hardly noticeable (esp. selected and highlighted):

<img width="336" alt="screen shot 2018-12-13 at 11 37 57" src="https://user-images.githubusercontent.com/1066083/49929642-9d8ed580-fecb-11e8-9a90-0aad5eae44c4.png">

With custom monochrome tint applied (BBBBBB in my case) everything looks much better - checkboxes aren't dark, icons are visible. But setting custom tint does not persist - after restarting PhpStorm the "Monochrome" checkbox is unchecked.

**Comment by ihorvorotnov** [comment]
Also, there's one additional issue with directory icons:

- if "Enable Directory Icons" is checked, I expect all directory icons on project tree to be replaced, including the default dir icon (a dir without special meaning). But it's not the case, native PhpStorm's dir icon is used. Check "upgrade" dir icon below:

<img width="174" alt="screen shot 2018-12-13 at 11 50 39" src="https://user-images.githubusercontent.com/1066083/49930659-bbf5d080-fecd-11e8-9456-0b30efeec81c.png">

- However, if "Enable UI Icons" is checked, those default dirs are replaced. Check the same "upgrade" dir below:

<img width="188" alt="screen shot 2018-12-13 at 11 55 06" src="https://user-images.githubusercontent.com/1066083/49930784-f7909a80-fecd-11e8-86e2-c4b3c8a23623.png">

I believe those icons should be applied with "Enable Directory Icons".

**Comment by mallowigi** [comment]
Thanks for the help! I've already fixed the runAction error.

Some points though:
- The lock icon is the default one, this is actually one of the few icons that haven;t been replaced by the plugin
- The filter applies to all icons, including "UI Icons" such as checkboxes. If they had been using graphics instead of icons this problem woudn't occur, but sadly there's nothing i can do since, as i said before, the monochrome filter is what it is, a filter for the whole icons in the UI. Perhaps I'll try to replace the checkbox icons with some ones without the blue in it, I am still not sure I want to though.
- The best course of action here would be to specify a light color for dark themes and dark color for light themes
- Directory icons have the same functionality as File Icons, e.g. identify a name pattern and apply an icon on it. Directories that do not depend on a pattern, such as regular directories, test directories or excluded directories, will have the default icon, which can be replaced through the UI Icons option, but that;s all.

**Comment by ihorvorotnov** [comment]
Awesome! Couple notes:

1. The lock icon (and those other few icons that haven't been replaced by the plugin)

It's ok for it to remain default. Just doesn't make sense that it becomes tinted with monochrome color even tough monochrome option is turned off (only UI icons are turned on).

2. Checkboxes/radios are ok. Not the best experience, but works quite well if you set the monochrome color with enough contrast.

3. Default dir icons - got it. Thanks for clarification.

Would you mind a PR with some additional directory / file regexes? I've checked the configs in pursuit of making WP's `mu-plugins` dir recognized as plugins dir (which it is) and see couple other places for improvements. Can do it today if you accept additions.

**Comment by mallowigi** [comment]
My bad, I actually replace the lock when using ui icons... It's albeit the default one but I did change the color. It's not related to the monochrome setting though, just use the same color.

Here's an updated version of all the fixes
[Atom File Icons IDEA-8.1.zip](https://github.com/mallowigi/a-file-icon-idea/files/2675717/Atom.File.Icons.IDEA-8.1.zip)

I don't mind PR, feel free.

**Comment by ihorvorotnov** [comment]
@mallowigi no new issues found so far. Additionally, made some additions to recognized files and dirs (and a new icon). Please check the PR #19 

Thanks!
