### ISSUE TITLE
File icons disappearing when refresh

### ISSUE THREAD

**Issue by hakuseki** [mallowigi/a-file-icon-idea#175]
In IntelliJ IDEA when refreshing the icons they show but then disappear

Might be caused by a NPE:

```
java.lang.NullPointerException: Parameter specified as non-null is null: method com.mallowigi.actions.IconToggleAction$selectedFallbackIcon$1.paintIcon, parameter c
	at com.mallowigi.actions.IconToggleAction$selectedFallbackIcon$1.paintIcon(IconToggleAction.kt)
	at com.intellij.ui.LayeredIcon.paintIcon(LayeredIcon.java:229)
	at com.intellij.ui.mac.touchbar.NST._drawIconIntoMemory(NST.java:412)
	at com.intellij.ui.mac.touchbar.NST._writeIconRaster(NST.java:390)
	at com.intellij.ui.mac.touchbar.NST._packItems(NST.java:299)
	at com.intellij.ui.mac.touchbar.NST.updateScrubberItems(NST.java:209)
	at com.intellij.ui.mac.touchbar.TBItemScrubber.updateItems(TBItemScrubber.java:52)
	at com.intellij.ui.mac.touchbar.TBItemScrubber.lambda$_createNativePeer$4(TBItemScrubber.java:97)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:819)
	at com.intellij.ui.mac.touchbar.TBItemScrubber.lambda$_createNativePeer$5(TBItemScrubber.java:97)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:265)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

IntelliJ IDEA 2021.1 (Ultimate Edition)
Build #IU-211.6693.111, built on April 6, 2021
macOS 11.2.3

**Comment by hakuseki** [comment]
still same issues though…

**Comment by mallowigi** [comment]
Really? Which IDE?

**Comment by hakuseki** [comment]
IntelliJ IDEA 2021.1.3 (Ultimate Edition)
Build #IU-211.7628.21, built on June 30, 2021
Runtime version: 11.0.11+9-b1341.60 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.4
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
