### ISSUE TITLE
Disabling UI icons without disabling PSI icons causes exception and missing icon in settings menu

### ISSUE THREAD

**Issue by liamjones** [mallowigi/a-file-icon-idea#183]
**Describe the bug**
If you disable the UI icons without disabling the PSI icons first then opening the settings menu from the toolbar throws an exception (seen below) and the "Enable PSI icons" menu entry's icon is missing. If you disable PSI Icons before you turn off UI Icons you don't have this problem.

**To Reproduce**
1. Install and enable plugin
2. Open Preferences and go to Appearance & Behaviour -> Atom Material Icon Settings
3. Confirm both "Enable UI Icons" and "Enable PSI Icons" are checked (default setting).
4. Uncheck "Enable UI Icons"
5. "OK" to save the settings
6. Open "Atom File Icon Settings" from the toolbar

**Expected Behavior**
"Enable PSI Icons" menu entry's icon displays and no exception is thrown.

**Environment**
WebStorm 2021.1.2
Build #WS-211.7442.26, built on May 24, 2021
Licensed to Liam Jones
Subscription is active until October 14, 2021.
Runtime version: 11.0.11+9-b1341.57 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 11.4
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: coderpillr.theme (1.0.0-rc.3), com.arcticicestudio.nord.jetbrains (0.13.0), com.github.mturlo.intellij.theme.spacegray (1.4.2), com.herokuapp.vuesion (1.9.2), com.intellij.ideolog (203.0.27.0), com.jetbrains.CyanTheme (1.2), com.jetbrains.darkPurpleTheme (1.2), com.markskelton.one-dark-theme (5.1.6), com.thvardhan.gradianto (4.4), com.atlassian.bitbucket.references (2021.1.165), quokka.js (1.0.301), rasarts.espresso.light.theme (1.2.0), izhangzhihao.rainbow.brackets (6.17), com.mallowigi (36.0)

**Screenshots**
With just UI Icons disabled in Preferences and PSI Icons still enabled:
![Screenshot 2021-06-09 at 17 15 16](https://user-images.githubusercontent.com/521341/121391695-9505a180-c946-11eb-868f-46d37ff86e2f.png)

With both UI Icons and PSI Icons disabled in Preferences:
![Screenshot 2021-06-09 at 17 18 29](https://user-images.githubusercontent.com/521341/121391937-d26a2f00-c946-11eb-8d69-007cc77581a5.png)

**Stack trace**
````
java.lang.NullPointerException: Parameter specified as non-null is null: method com.mallowigi.actions.IconToggleAction$selectedFallbackIcon$1.paintIcon, parameter c
	at com.mallowigi.actions.IconToggleAction$selectedFallbackIcon$1.paintIcon(IconToggleAction.kt)
	at com.intellij.ui.LayeredIcon.paintIcon(LayeredIcon.java:229)
	at com.intellij.ui.mac.touchbar.NST._drawIconIntoMemory(NST.java:412)
	at com.intellij.ui.mac.touchbar.NST._writeIconRaster(NST.java:390)
	at com.intellij.ui.mac.touchbar.NST._packItems(NST.java:299)
	at com.intellij.ui.mac.touchbar.NST.updateScrubberItems(NST.java:209)
	at com.intellij.ui.mac.touchbar.TBItemScrubber.updateItems(TBItemScrubber.java:52)
	at com.intellij.ui.mac.touchbar.TBItemScrubber.lambda$_createNativePeer$4(TBItemScrubber.java:97)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:819)
	at com.intellij.ui.mac.touchbar.TBItemScrubber.lambda$_createNativePeer$5(TBItemScrubber.java:97)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:265)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
````

**Comment by mallowigi** [comment]
Can't reproduce on latest version. Please check if it happenss to you.

**Comment by liamjones** [comment]
Yep, it's looking better in the latest version.

There's still a minor visual glitch in that the icon still doesn't display correctly - e.g. it's a grey square (like the first screenshot above) rather than a grey version of the 3d box icon (like the second screenshot above) but the main issue, the NPE, is gone.
