### ISSUE TITLE
Sometimes have NPE

### ISSUE THREAD

**Issue by godfather1103** [mallowigi/a-file-icon-idea#215]
**Describe the bug**

java.lang.NullPointerException
	at com.intellij.util.messages.impl.BaseBusConnection.subscribe(BaseBusConnection.java:38)
	at com.mallowigi.tree.ArrowIconsComponent.initComponent(ArrowIconsComponent.kt:61)
	at com.mallowigi.tree.ArrowIconsComponent.pluginLoaded(ArrowIconsComponent.kt:54)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeMethod(MessageBusImpl.java:645)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:624)
	at com.intellij.util.messages.impl.MessageBusImpl.access$300(MessageBusImpl.java:33)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.executeOrAddToQueue(MessageBusImpl.java:208)
	at com.intellij.util.messages.impl.CompositeMessageBus$ToDirectChildrenMessagePublisher.publish(CompositeMessageBus.java:105)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:166)
	at com.sun.proxy.$Proxy83.pluginLoaded(Unknown Source)
	at com.intellij.ide.plugins.DynamicPlugins$loadPlugin$1.run(DynamicPlugins.kt:828)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:936)
	at com.intellij.ide.plugins.DynamicPlugins.loadPlugin(DynamicPlugins.kt:808)
	at com.intellij.ide.plugins.DynamicPlugins.loadPlugin(DynamicPlugins.kt:790)
	at com.intellij.ide.plugins.PluginInstaller.installAndLoadDynamicPlugin(PluginInstaller.java:392)
	at com.intellij.ide.plugins.newui.MyPluginModel.lambda$apply$0(MyPluginModel.java:176)
	at com.intellij.ide.plugins.InstalledPluginsState.trackPluginInstallation(InstalledPluginsState.java:189)
	at com.intellij.ide.plugins.newui.MyPluginModel.apply(MyPluginModel.java:175)
	at com.intellij.ide.plugins.PluginManagerConfigurable.apply(PluginManagerConfigurable.java:1627)
	at com.intellij.openapi.wm.impl.welcomeScreen.PluginsTabFactory$MyDefaultWelcomeScreenTab$2.ancestorRemoved(PluginsTabFactory.java:81)
	at java.desktop/javax.swing.AncestorNotifier.fireAncestorRemoved(AncestorNotifier.java:108)
	at java.desktop/javax.swing.AncestorNotifier.componentHidden(AncestorNotifier.java:208)
	at java.desktop/java.awt.Component.processComponentEvent(Component.java:6487)
	at java.desktop/java.awt.Component.processEvent(Component.java:6432)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:887)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:442)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:494)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
**To Reproduce**

Update other plug-ins. When the plug-in supports auto restart, it is possible to reproduce the bug.

**Expected Behavior**

**Environment**

IntelliJ IDEA 2021.2.1 (Community Edition)
Build #IC-212.5080.55, built on August 24, 2021
Runtime version: 11.0.11+9-b1504.16 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.5.2
GC: G1 Young Generation, G1 Old Generation
Memory: 5120M
Cores: 8
Registry: scala.erase.compiler.process.jdk.once=false
Non-Bundled Plugins: com.jetbrains.plugins.ini4idea (212.4746.57), net.vektah.codeglance (1.5.4), com.godfather1103.intellijPlugin (3.2), commit-template-check-plugin (1.8.0), com.failfast (2.0.4), com.mallowigi (40.0.0), com.bruce.intellijpluin.stackoverflow (1.2.1), com.alibaba.p3c.smartfox (2.1.1), GrepConsole (11.10.211.6086.0), com.github.wangji92.arthas.plugin (2.32), Docker (212.5080.8), com.intellij.ideolog (203.0.27.0), mobi.hsz.idea.gitignore (4.2.0), PythonCore (212.5080.74), idea.plugin.protoeditor (212.5080.8), MavenRunHelper (4.16.212.000.0), org.jetbrains.kotlin (212-1.5.30-release-409-IJ4638.7), com.baomidou.plugin.idea.mybatisx (1.5.0), org.intellij.scala (2021.2.22)
Kotlin: 212-1.5.30-release-409-IJ4638.7
**Screenshots**

![Uploading iShot2021-09-15 09.16.08.png…]()

**Comment by godfather1103** [comment]
<img width="860" alt="iShot2021-09-15 09 16 08" src="https://user-images.githubusercontent.com/11797964/133355047-644ceea5-1efe-4060-a9bb-aba75dfe9e2d.png">

**Comment by godfather1103** [comment]
I will try to fix the bug. Please don't close the issue for a week

**Comment by serpro69** [comment]
Same issue here, version 40.0.0 seems to have broken quite a bit of things.
Folder icons aren't displaying properly also after the update.

**Comment by mallowigi** [comment]
I'll try to change a bit the connect feature. For other issues, please create tickets accordingly

**Comment by godfather1103** [comment]
Thinks
