### ISSUE TITLE
java.lang.Throwable: Control-flow exceptions (like ProcessCanceledException) should never be logged: ignore for explicitly started processes or rethrow to handle on the outer process level

### ISSUE THREAD

**Issue by cw209** [mallowigi/a-file-icon-idea#243]
webStorm(windows)
50.2.0
stacktrace.txt
java.lang.Throwable: Control-flow exceptions (like ProcessCanceledException) should never be logged: ignore for explicitly started processes or rethrow to handle on the outer process level
	at com.intellij.openapi.diagnostic.Logger.ensureNotControlFlow(Logger.java:234)
	at com.intellij.idea.IdeaLogger.doLogError(IdeaLogger.java:198)
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:189)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:208)
	at com.mallowigi.icons.associations.Associations.findAssociation(Associations.kt:61)
	at com.mallowigi.icons.providers.AbstractFileIconProvider.findAssociation(AbstractFileIconProvider.kt:103)
	at com.mallowigi.icons.providers.AbstractFileIconProvider.findIcon(AbstractFileIconProvider.kt:68)
	at com.mallowigi.icons.providers.AbstractFileIconProvider.getIcon(AbstractFileIconProvider.kt:52)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:21)
	at com.intellij.ide.FileIconPatcherImpl.getIcon(FileIconPatcherImpl.java:37)
	at com.intellij.util.IconUtil.getProvidersIcon(IconUtil.java:222)
	at com.intellij.util.IconUtil.computeFileIcon(IconUtil.java:155)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters.lambda$updateFileIconAsynchronously$7(EditorsSplitters.java:430)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:521)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:78)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:161)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:118)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:115)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:78)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:407)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:187)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.intellij.openapi.progress.ProcessCanceledException
	at com.intellij.openapi.progress.EmptyProgressIndicatorBase.checkCanceled(EmptyProgressIndicatorBase.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.doCheckCanceled(CoreProgressManager.java:138)
	at com.intellij.openapi.progress.ProgressManager.checkCanceled(ProgressManager.java:231)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.lambda$setCheckCanceledAction$18(ExtensionPointImpl.java:1102)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getThreadSafeAdapterList(ExtensionPointImpl.java:330)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.findExtensionByExactClass(ExtensionPointImpl.java:1051)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.findExtension(ExtensionPointImpl.java:1000)
	at com.intellij.openapi.extensions.ExtensionPointName.findExtension(ExtensionPointName.java:112)
	at com.intellij.DynamicBundle.findLanguageBundle(DynamicBundle.java:95)
	at com.intellij.DynamicBundle.findBundle(DynamicBundle.java:45)
	at com.intellij.AbstractBundle.resolveResourceBundle(AbstractBundle.java:144)
	at com.intellij.AbstractBundle.getResourceBundle(AbstractBundle.java:115)
	at com.intellij.AbstractBundle.getMessage(AbstractBundle.java:42)
	at com.mallowigi.config.AtomSettingsBundle.message(AtomSettingsBundle.kt:41)
	at com.mallowigi.icons.associations.Associations.findAssociation(Associations.kt:56)
	... 36 more

**Comment by mallowigi** [comment]
steps?
