### ISSUE TITLE
Atom Material Icons exception

### ISSUE THREAD

**Issue by makucg** [mallowigi/a-file-icon-idea#281]
**Describe the bug**

IntelliJ show random errors after start.

**To Reproduce**

1. Start IntelliJ.

**Expected Behavior**

Nothing.

**Environment**
IntelliJ IDEA 2022.1 (Ultimate Edition)
Build #IU-221.5080.210, built on April 12, 2022
Runtime version: 17.0.2+8-b396.4 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Non-Bundled Plugins:
    some.awesome (1.14)
    name.kropp.intellij.makefile (221.5080.126)
    com.markskelton.one-dark-theme (5.5.2)
    google-java-format (1.15.0.0)
    com.mallowigi (64.0.0)
    Batch Scripts Support (1.0.13)
    com.intellij.aspectj (221.5080.169)
    ru.adelf.idea.dotenv (2022.1)
    izhangzhihao.rainbow.brackets (6.21)
    com.haulmont.jpab (2022.2.2-221)

Kotlin: 221-1.6.20-release-285-IJ5080.210

Atom Material Icons (64.0.0)

**Screenshots**

java.lang.IllegalAccessError: class com.intellij.ui.svg.SvgCacheManager$Companion (in unnamed module @0x59e5b960) cannot access class sun.awt.image.SunWritableRaster (in module java.desktop) because module java.desktop does not export sun.awt.image to unnamed module @0x59e5b960
	at com.intellij.ui.svg.SvgCacheManager$Companion.readImage(SvgCacheManager.kt:47)
	at com.intellij.ui.svg.SvgCacheManager.loadFromCache(SvgCacheManager.kt:106)
	at com.intellij.util.SVGLoader.loadFromClassResource(SVGLoader.java:166)
	at com.intellij.util.ImageLoader.loadByDescriptorWithoutCache(ImageLoader.java:277)
	at com.intellij.util.ImageLoader.loadByDescriptor(ImageLoader.java:234)
	at com.intellij.util.ImageLoader.loadImage(ImageLoader.java:159)
	at com.intellij.openapi.util.ImageDataByUrlLoader.loadImage(ImageDataByUrlLoader.java:89)
	at com.intellij.openapi.util.IconLoader$CachedImageIcon.loadImage(IconLoader.java:979)
	at com.intellij.openapi.util.IconLoader$ScaledIconCache.getOrScaleIcon(IconLoader.java:1048)
	at com.intellij.openapi.util.IconLoader$CachedImageIcon.getRealIcon(IconLoader.java:866)
	at com.intellij.openapi.util.IconLoader$CachedImageIcon.getIconHeight(IconLoader.java:799)
	at icons.AtomIcons.loadIconWithFallback(AtomIcons.kt:120)
	at com.mallowigi.icons.providers.DefaultFileIconProvider.getIcon(DefaultFileIconProvider.kt:50)
	at com.mallowigi.icons.providers.AbstractFileIconProvider.loadIcon(AbstractFileIconProvider.kt:84)
	at com.mallowigi.icons.providers.AbstractFileIconProvider.getIconForAssociation$lambda-0(AbstractFileIconProvider.kt:76)
	at java.base/java.util.Optional.map(Optional.java:260)
	at com.mallowigi.icons.providers.AbstractFileIconProvider.getIconForAssociation(AbstractFileIconProvider.kt:76)
	at com.mallowigi.icons.providers.AbstractFileIconProvider.findIcon(AbstractFileIconProvider.kt:69)
	at com.mallowigi.icons.providers.AbstractFileIconProvider.getIcon(AbstractFileIconProvider.kt:52)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:21)
	at com.intellij.ide.FileIconPatcherImpl.getIcon(FileIconPatcherImpl.java:37)
	at com.intellij.util.IconUtil.getProvidersIcon(IconUtil.java:215)
	at com.intellij.util.IconUtil.computeFileIcon(IconUtil.java:149)
	at com.intellij.util.IconUtil.lambda$static$0(IconUtil.java:137)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:247)
	at com.intellij.ui.DeferredIconImpl.lambda$scheduleEvaluation$1(DeferredIconImpl.java:172)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:99)
	at com.intellij.ui.DeferredIconImpl.lambda$scheduleEvaluation$2(DeferredIconImpl.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1152)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:158)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:115)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:58)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:58)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:112)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:96)
	at com.intellij.ui.DeferredIconImpl.lambda$scheduleEvaluation$5(DeferredIconImpl.java:171)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:241)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:214)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:203)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by makucg** [comment]
I still have this problem. :(

**Comment by mallowigi** [comment]
Please provide your settings, thanks

**Comment by makucg** [comment]
Where can I find it?
