### ISSUE TITLE
The plugin does not work properly and reports an error

### ISSUE THREAD

**Issue by kuolemax** [mallowigi/a-file-icon-idea#297]
**Describe the bug**
Atom Materical Icons don't work in IDEA-U 2022.2 EAP

**To Reproduce**
1. update IU from 2022.1.3 to 2022.2-eap use Jetbrains toolbox app
2. launch IU
3. enable ide.experimental.ui (disabled still)

**Expected Behavior**
it works

**Environment**

OS: ArchLinux
Kernel: 5.18.7-arch1-1
DE: Plasma 5.25.2
WM: KWin

> IntelliJ IDEA 2022.2 EAP (Ultimate Edition)
> Build #IU-222.3244.4, built on June 29, 2022
> Runtime version: 11.0.14.1-internal+0-adhoc.runner.JetBrainsRuntime amd64
> VM: OpenJDK 64-Bit Server VM by Oracle Corporation

Plugin version: 65.1.0

* If needed a list of enabled plugins -->
- IDEA's own plugin
- Atom Material Icons
- GitToolBox
- JavaFX Runtime for Plugins
- Material Theme UI Lite
- Translation

**Screenshots**

![image](https://user-images.githubusercontent.com/25677528/176632626-2db2afe9-b996-4b47-81ed-a0b44db785cb.png)

**Stacktrace**

```text
com.intellij.diagnostic.PluginException: Cannot create extension (class=com.mallowigi.config.AtomConfigTopHitProvider) [Plugin: com.mallowigi]
	at com.intellij.serviceContainer.ComponentManagerImpl.createError(ComponentManagerImpl.kt:945)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.doCreateInstance(XmlExtensionAdapter.kt:70)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.kt:31)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:447)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:299)
	at com.intellij.openapi.extensions.ExtensionPointName.processWithPluginDescriptor(ExtensionPointName.java:143)
	at com.intellij.ide.ui.OptionsTopHitProvider$Activity.cacheAll(OptionsTopHitProvider.java:177)
	at com.intellij.ide.ui.OptionsTopHitProvider$Activity.preload(OptionsTopHitProvider.java:165)
	at com.intellij.idea.ApplicationLoader$executePreloadActivity$1.run(ApplicationLoader.kt:521)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.idea.ApplicationLoader.executePreloadActivity(ApplicationLoader.kt:511)
	at com.intellij.idea.ApplicationLoader.access$executePreloadActivity(ApplicationLoader.kt:1)
	at com.intellij.idea.ApplicationLoader$executePreloadActivities$2.run(ApplicationLoader.kt:576)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: com.intellij.diagnostic.PluginException: Cannot load class com.mallowigi.config.AtomConfigTopHitProvider (
  error: com/mallowigi/config/AtomConfigTopHitProvider has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0,
  classLoader=PluginClassLoader(plugin=PluginDescriptor(name=Atom Material Icons, id=com.mallowigi, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/222.3244.4.plugins/Atom Material Icons, version=65.1.0, package=null, isBundled=false), packagePrefix=null, instanceId=119, state=active)
)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:411)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:239)
	at com.intellij.serviceContainer.ComponentManagerImplKt.doLoadClass(ComponentManagerImpl.kt:1468)
	at com.intellij.serviceContainer.ComponentManagerImplKt.access$doLoadClass(ComponentManagerImpl.kt:1)
	at com.intellij.serviceContainer.ComponentManagerImpl.loadClass(ComponentManagerImpl.kt:835)
	at com.intellij.openapi.extensions.impl.InterfaceExtensionImplementationClassResolver.resolveImplementationClass(InterfaceExtensionImplementationClassResolver.kt:24)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.doCreateInstance(XmlExtensionAdapter.kt:49)
	... 21 more
Caused by: java.lang.UnsupportedClassVersionError: com/mallowigi/config/AtomConfigTopHitProvider has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
	at java.base/java.lang.ClassLoader.defineClass2(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1109)
	at com.intellij.util.lang.UrlClassLoader.consumeClassData(UrlClassLoader.java:253)
	at com.intellij.util.lang.ZipResourceFile.findClass(ZipResourceFile.java:114)
	at com.intellij.util.lang.JarLoader.findClass(JarLoader.java:63)
	at com.intellij.util.lang.ClassPath.findClassInLoader(ClassPath.java:246)
	at com.intellij.util.lang.ClassPath.findClassWithoutCache(ClassPath.java:235)
	at com.intellij.util.lang.ClassPath.findClass(ClassPath.java:202)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:403)
	... 27 more

```

**Comment by kuolemax** [comment]
By the way, it works fine on my macbook

**Comment by kuolemax** [comment]
now 2022.2 release and plugin version 65.1.0 still has this problem

**Comment by t0rb3n** [comment]
@kuolemax Switching the Boot Java Runtime of the IDE to Java 18 or higher (in my case 18.0.2) worked and the plugin now loads fine. Take a look [here](https://intellij-support.jetbrains.com/hc/en-us/articles/206544879-Selecting-the-JDK-version-the-IDE-will-run-under) on how to change to Boot Java Runtime.

**Comment by kuolemax** [comment]
> @kuolemax Switching the Boot Java Runtime of the IDE to Java 18 or higher (in my case 18.0.2) worked and the plugin now loads fine. Take a look [here](https://intellij-support.jetbrains.com/hc/en-us/articles/206544879-Selecting-the-JDK-version-the-IDE-will-run-under) on how to change to Boot Java Runtime.

Thanks! I found out that I was using java 11 all the time and everything worked fine after I switched jbr to 17.
