### ISSUE TITLE
com.intellij.diagnostic.PluginException: 798 ms to call on EDT ActionGroup#getChildren@MainToolbar 

### ISSUE THREAD

**Issue by CrazyBoy49z** [mallowigi/a-file-icon-idea#334]
**Describe the bug**
```
com.intellij.diagnostic.PluginException: 798 ms to call on EDT ActionGroup#getChildren@MainToolbar (com.mallowigi.actions.ActionGroup). Revise AnAction.getActionUpdateThread property [Plugin: com.mallowigi]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:83)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.computeOnEdt(ActionUpdater.java:255)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:203)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:161)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$new$2(ActionUpdater.java:125)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$getGroupChildren$24(ActionUpdater.java:536)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.getGroupChildren(ActionUpdater.java:544)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.iterateGroupChildren(ActionUpdater.java:678)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild(ActionUpdater.java:579)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroup$23(ActionUpdater.java:529)
	at com.intellij.util.containers.ContainerUtil.concat(ContainerUtil.java:1406)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup(ActionUpdater.java:529)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandActionGroup(ActionUpdater.java:309)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroupAsync$14(ActionUpdater.java:377)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroupAsync$15(ActionUpdater.java:396)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1086)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$tryRunReadActionAndCancelBeforeWrite$19(ActionUpdater.java:428)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:128)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.tryRunReadActionAndCancelBeforeWrite(ActionUpdater.java:424)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroupAsync$16(ActionUpdater.java:396)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:190)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:666)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:622)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:590)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:177)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:365)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroupAsync$17(ActionUpdater.java:395)
	at io.opentelemetry.context.Context.lambda$wrap$1(Context.java:212)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:243)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:216)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:205)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: java.lang.Throwable: EDT-trace-unknown
```

**Environment**
PhpStorm 2022.3
Build #PS-223.7571.212, built on December 1, 2022
Licensed to Yurij Finiv
Subscription is active until September 17, 2023.
Runtime version: 17.0.5+1-b653.14 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.6.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
    editor.focus.mode.color.light=415967
    debugger.new.tool.window.layout=true
    ide.windowSystem.autoShowProcessPopup=true
    run.processes.with.pty=TRUE
    ide.new.editor.tabs.vertical.borders=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=415967

Non-Bundled Plugins:
    io.aesy.regex101 (0.2)
    LiveTemplatePreview (0.3)
    com.mroche.JsonHelper (1.2.0)
    MultiHighlight (3.0.0)
    zielu.gittoolbox (213.10.2)
    mobi.hsz.idea.gitignore (4.4.4)
    com.materkey.codepoints (1.0.2)
    ideanginx9 (0.1.9)
    lermitage.intellij.battery.status (1.25)
    com.unger1984.npmdependencychecker (0.0.3)
    com.intellij.properties (223.7571.117)
    com.github.googee.laravelbuilder (0.1.3)
    Key Promoter X (2022.3)
    krasa.CpuUsageIndicator (1.14)
    com.mallowigi (80.0.0)
    String Manipulation (9.6.1)
    cc.moky.intellij.plugin.svga-support (1.0.8)
    com.wakatime.intellij.plugin (14.1.2)
    com.github.czy211.licensetemplate (2.0.0)
    com.github.inxilpro.intellijalpine (v0.4.2)
    io.snyk.snyk-intellij-plugin (2.4.49)
    com.wix.sasslint (1.1.2)
    cat.dcat.jbplug.mactabbing (1.1.0)
    com.guohanlin.JsonToAnyLanguage (1.1.0)
    com.pestphp.pest-intellij (1.8.3)
    net.rentalhost.plugins.php.hammer (0.18.0)
    com.funivan.idea.phpClean (2022.08.30)
    ru.adelf.idea.dotenv (2022.3)
    de.espend.idea.php.annotation (8.3.0)
    dev.nybroe.collector (0.4.0)
    com.kalessil.phpStorm.phpInspectionsEA (4.0.7.1)
    fr.adrienbrault.idea.symfony2plugin (2022.1.237)
    com.chrisrm.idea.MaterialThemeUI (8.3.2)
    com.mallowigi.colorHighlighter (14.0.0)
    bundled-phpstorm-help (223.7571.212)
    com.laravel_idea.plugin (6.2.2.223)
    cn.yiiguxing.plugin.translate (3.4.0)
    org.i18nally.jetbrainsideplugin (1.4.1.4)
    lermitage.intellij.worldclock (1.5.1)
    com.github.chengpohi (1.9.8)
    ski.chrzanow.foldableprojectview (1.1.4)
    lermitage.intellij.extratci (1.24.0)
    lermitage.intellij.iconviewer (1.19)
    izhangzhihao.rainbow.brackets (2022.3.5)

**Comment by mallowigi** [comment]
will be fixed next version
