### ISSUE TITLE
WebStorm: FileNotFoundException for icons which _do_ exist.

### ISSUE THREAD

**Issue by jezmck** [mallowigi/a-file-icon-idea#352]
**Describe the bug**
Sometimes, when opening standard files I get the following, or similar, for different icons.

> java.io.FileNotFoundException: /icons/files/githubActions.svg (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
	at icons.AtomIcons.loadSVGIcon(AtomIcons.kt:104)
	at icons.AtomIcons.loadIconWithFallback(AtomIcons.kt:115)
	at com.mallowigi.icons.providers.DefaultFileIconProvider.getIcon(DefaultFileIconProvider.kt:40)
	at com.mallowigi.icons.providers.AbstractFileIconProvider.loadIcon(AbstractFileIconProvider.kt:83)
	at com.mallowigi.icons.providers.AbstractFileIconProvider.access$loadIcon(AbstractFileIconProvider.kt:40)
	at com.mallowigi.icons.providers.AbstractFileIconProvider$getIconForAssociation$1.invoke(AbstractFileIconProvider.kt:75)
	at com.mallowigi.icons.providers.AbstractFileIconProvider$getIconForAssociation$1.invoke(AbstractFileIconProvider.kt:75)
	at com.mallowigi.icons.providers.AbstractFileIconProvider.getIconForAssociation$lambda$0(AbstractFileIconProvider.kt:75)
	at java.base/java.util.Optional.map(Optional.java:260)
	at com.mallowigi.icons.providers.AbstractFileIconProvider.getIconForAssociation(AbstractFileIconProvider.kt:75)
	at com.mallowigi.icons.providers.AbstractFileIconProvider.findIcon(AbstractFileIconProvider.kt:67)
	at com.mallowigi.icons.providers.AbstractFileIconProvider.getIcon(AbstractFileIconProvider.kt:50)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:21)
	at com.intellij.ide.FileIconPatcherImpl.getIcon(FileIconPatcherImpl.java:37)
	at com.intellij.util.IconUtil.getProvidersIcon(IconUtil.java:227)
	at com.intellij.util.IconUtil.computeFileIcon(IconUtil.java:156)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters.updateFileIconAsynchronously$lambda$10(EditorsSplitters.kt:414)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor.callWrapped(NonBlockingReadActionImpl.java:746)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor$MonitoredComputation.call(NonBlockingReadActionImpl.java:778)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:573)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:537)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1111)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:71)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:128)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:109)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:68)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:68)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:106)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:71)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:537)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:444)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:243)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:208)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Environment**
WebStorm 2022.3.3
Build #WS-223.8836.27, built on March 1, 2023
Licensed to Jez McKean
You have a perpetual fallback license for this version.
Subscription is active until January 17, 2024.
Runtime version: 17.0.6+1-b653.34 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.2.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
    ide.intellij.laf.enable.animation=true
    ide.balloon.shadow.size=0
    ide.images.show.chessboard=true

Non-Bundled Plugins:
    manjaro.mpb (1.8)
    cn.haojiyou.CodeGlance3 (2.1.1-2021.1.3)
    com.github.copilot (1.2.4.2459)
    ir.msdehghan.plugins.ansible (0.92)
    com.github.zzehring.intellijjsonnet (0.1.0)
    com.mallowigi.idea (20.0.0)
    name.kropp.intellij.makefile (223.8214.6)
    awesome.console (0.1337.12)
    org.intellij.plugins.postcss (223.7571.117)
    com.jinsihou.react.snippets (1.1.1)
    com.intellij.swagger (223.8214.6)
    net.seesharpsoft.intellij.plugins.csv (3.1.0-223)
    com.mallowigi (85.1.0)
    mobi.hsz.idea.gitignore (4.4.4)
    de.timo_reymann.intellij-mjml-support (2.4.0)
    mdx.js (223.8214.16)
    com.rxliuli.vite-jetbrains-plugin (0.2.2)
    com.emberjs (2022.3.2)

**Comment by jezmck** [comment]
:( It's still happening BTW.

**Comment by mallowigi** [comment]
I can't reproduce. Are you using custom associations ?
