### ISSUE TITLE
91.0.0 crashes Idea 2023.1.2 on startup

### ISSUE THREAD

**Issue by Sn0wFox** [mallowigi/a-file-icon-idea#375]
**Describe the bug**

91.0.0 crashes Idea 2023.1.2 on startup. The IDE stays unresponsive and most components won't load. A stacktrace from the logs is attached at the bottom, where the issue is clearly blamed on this plugin.

Happens with the new UI, as noted in the below environment. However I did not test it with the old UI.

**To Reproduce**

1. Install plugin version 91.0.0
2. Restart the IDE

Note that version 90.0.0 works fine.

**Expected Behavior**

The IDE should start correctly.

**Environment**

```
IntelliJ IDEA 2023.1.2 (Ultimate Edition)
Build #IU-231.9011.34, built on May 16, 2023
Licensed to REDACTED
Runtime version: 17.0.6+10-b829.9 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.4
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Kotlin: 231-1.8.21-IJ9011.34
```

**Screenshots**

Not applicable

**Logs**

<details><summary>Stacktrace</summary>

```
2023-06-16 11:31:18,962 [  14728] SEVERE - #c.i.u.c.Invoker - Method com/mallowigi/icons/svgpatchers/MainSvgPatcher.forPath(Ljava/lang/String;)Lcom/intellij/util/SVGLoader$SvgElementColorPatcher; is abstract
java.lang.AbstractMethodError: Method com/mallowigi/icons/svgpatchers/MainSvgPatcher.forPath(Ljava/lang/String;)Lcom/intellij/util/SVGLoader$SvgElementColorPatcher; is abstract
	at com.mallowigi.icons.svgpatchers.MainSvgPatcher.forPath(MainSvgPatcher.kt)
	at com.intellij.util.SVGLoader.loadFromClassResource(SVGLoader.kt:78)
	at com.intellij.util.SVGLoader.loadFromClassResource$default(SVGLoader.kt:70)
	at com.intellij.ui.RasterizedImageDataLoaderKt.loadPatched(RasterizedImageDataLoader.kt:216)
	at com.intellij.ui.RasterizedImageDataLoaderKt.loadRasterized(RasterizedImageDataLoader.kt:127)
	at com.intellij.ui.RasterizedImageDataLoaderKt.access$loadRasterized(RasterizedImageDataLoader.kt:1)
	at com.intellij.ui.RasterizedImageDataLoader.loadImage(RasterizedImageDataLoader.kt:44)
	at com.intellij.openapi.util.CachedImageIcon.loadImage$intellij_platform_util_ui(CachedImageIcon.kt:269)
	at com.intellij.openapi.util.ScaledIconCache.getOrScaleIcon(ScaledIconCache.kt:46)
	at com.intellij.openapi.util.CachedImageIcon.getRealIcon$intellij_platform_util_ui(CachedImageIcon.kt:151)
	at com.intellij.openapi.util.CachedImageIcon.getIconWidth(CachedImageIcon.kt:104)
	at com.intellij.ui.SimpleColoredComponent.computePreferredSize(SimpleColoredComponent.java:433)
	at com.intellij.ui.SimpleColoredComponent.getPreferredSize(SimpleColoredComponent.java:401)
	at com.intellij.ui.tree.ui.DefaultTreeUI$2.getNodeDimensions(DefaultTreeUI.java:564)
	at java.desktop/javax.swing.tree.AbstractLayoutCache.getNodeDimensions(AbstractLayoutCache.java:497)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.updatePreferredSize(VariableHeightLayoutCache.java:1344)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.createNodeAt(VariableHeightLayoutCache.java:767)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.treeNodesInserted(VariableHeightLayoutCache.java:476)
	at com.intellij.ui.tree.ui.DefaultTreeUI$3.treeNodesInserted(DefaultTreeUI.java:600)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.treeNodesInserted(BasicTreeUI.java:4368)
	at com.intellij.database.view.TreeFilterModel$OriginModelListener.treeNodesInserted(TreeFilterModel.kt:269)
	at com.intellij.util.ui.tree.TreeModelListenerList.treeNodesInserted(TreeModelListenerList.java:85)
	at com.intellij.ui.tree.AsyncTreeModel.treeNodesInserted(AsyncTreeModel.java:364)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.setNode(AsyncTreeModel.java:698)
	at com.intellij.ui.tree.AsyncTreeModel$Command.accept(AsyncTreeModel.java:475)
	at com.intellij.ui.tree.AsyncTreeModel.lambda$submit$12(AsyncTreeModel.java:293)
	at com.intellij.util.concurrency.Invoker$Wrapper.get(Invoker.java:327)
	at com.intellij.util.concurrency.Invoker$Wrapper.get(Invoker.java:318)
	at com.intellij.util.concurrency.Invoker$Task.run(Invoker.java:304)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:185)
	at com.intellij.util.concurrency.Invoker.lambda$offerSafely$0(Invoker.java:165)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:194)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:456)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:122)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:788)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:758)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:667)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$7(IdeEventQueue.kt:571)
	at com.intellij.openapi.application.impl.ApplicationImpl.withoutImplicitRead(ApplicationImpl.java:1446)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:571)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:995)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:995)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
2023-06-16 11:31:18,988 [  14754] SEVERE - #c.i.u.c.Invoker - IntelliJ IDEA 2023.1.2  Build #IU-231.9011.34
2023-06-16 11:31:18,989 [  14755] SEVERE - #c.i.u.c.Invoker - JDK: 17.0.6; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2023-06-16 11:31:18,990 [  14756] SEVERE - #c.i.u.c.Invoker - OS: Mac OS X
2023-06-16 11:31:18,993 [  14759] SEVERE - #c.i.u.c.Invoker - Plugin to blame: Atom Material Icons version: 91.0.0
2023-06-16 11:31:19,006 [  14772]   WARN - #c.i.i.s.p.i.BundledSharedIndexPostStartupActivity - Skipped 1 pre-built shared indexes: bundled-js-predefined-1d06a55b98c1-e95fd0b84d23-JavaScript-IU-231.9011.34
...
2023-06-16 11:31:20,885 [  16651] SEVERE - #c.i.o.a.i.FlushQueue - Receiver class com.mallowigi.icons.svgpatchers.MainSvgPatcher does not define or inherit an implementation of the resolved method 'abstract com.intellij.util.SVGLoader$SvgElementColorPatcher forPath(java.lang.String)' of interface com.intellij.util.SVGLoader$SvgElementColorPatcherProvider.
java.lang.AbstractMethodError: Receiver class com.mallowigi.icons.svgpatchers.MainSvgPatcher does not define or inherit an implementation of the resolved method 'abstract com.intellij.util.SVGLoader$SvgElementColorPatcher forPath(java.lang.String)' of interface com.intellij.util.SVGLoader$SvgElementColorPatcherProvider.
	at com.intellij.util.ImageLoaderKt.loadByDescriptor(ImageLoader.kt:521)
	at com.intellij.util.ImageLoaderKt.access$loadByDescriptor(ImageLoader.kt:1)
	at com.intellij.util.ImageLoader.loadImage(ImageLoader.kt:86)
	at com.intellij.util.ImageLoader.loadImage$default(ImageLoader.kt:72)
	at com.intellij.openapi.ui.ImageDataByPathLoader.loadImage(ImageDataByPathLoader.kt:94)
	at com.intellij.openapi.util.CachedImageIcon.loadImage$intellij_platform_util_ui(CachedImageIcon.kt:269)
	at com.intellij.openapi.util.ScaledIconCache.getOrScaleIcon(ScaledIconCache.kt:46)
	at com.intellij.openapi.util.CachedImageIcon.getRealIcon$intellij_platform_util_ui(CachedImageIcon.kt:151)
	at com.intellij.openapi.util.CachedImageIcon.getIconWidth(CachedImageIcon.kt:104)
	at com.intellij.ui.tree.ui.DefaultControl.getWidth(DefaultControl.java:42)
	at com.intellij.ui.tree.ui.ClassicPainter.getRendererOffset(ClassicPainter.java:33)
	at com.intellij.ui.tree.ui.DefaultTreeUI$2.getNodeDimensions(DefaultTreeUI.java:570)
	at java.desktop/javax.swing.tree.AbstractLayoutCache.getNodeDimensions(AbstractLayoutCache.java:497)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.updatePreferredSize(VariableHeightLayoutCache.java:1344)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(VariableHeightLayoutCache.java:1465)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(VariableHeightLayoutCache.java:1272)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.rebuild(VariableHeightLayoutCache.java:728)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.setModel(VariableHeightLayoutCache.java:111)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.configureLayoutCache(BasicTreeUI.java:2131)
	at com.intellij.ui.tree.ui.DefaultTreeUI.configureLayoutCache(DefaultTreeUI.java:435)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.completeUIInstall(BasicTreeUI.java:840)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.installUI(BasicTreeUI.java:800)
	at java.desktop/javax.swing.JComponent.setUI(JComponent.java:733)
	at java.desktop/javax.swing.JTree.setUI(JTree.java:760)
	at com.intellij.ui.treeStructure.Tree.setUI(Tree.java:124)
	at java.desktop/javax.swing.JTree.updateUI(JTree.java:781)
	at com.intellij.util.IJSwingUtilities.updateComponentTreeUI(IJSwingUtilities.java:95)
	at com.intellij.ide.ui.laf.LafManagerImplKt.updateUI(LafManagerImpl.kt:1457)
	at com.intellij.ide.ui.laf.LafManagerImplKt.access$updateUI(LafManagerImpl.kt:1)
	at com.intellij.ide.ui.laf.LafManagerImpl.updateUI(LafManagerImpl.kt:815)
	at com.mallowigi.icons.AtomSVGPatchersListener.initComponent$lambda$3(AtomSVGPatchersListener.kt:70)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:456)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:122)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:788)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:758)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:667)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$7(IdeEventQueue.kt:571)
	at com.intellij.openapi.application.impl.ApplicationImpl.withoutImplicitRead(ApplicationImpl.java:1446)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:571)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:995)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:995)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
2023-06-16 11:31:20,890 [  16656] SEVERE - #c.i.o.a.i.FlushQueue - IntelliJ IDEA 2023.1.2  Build #IU-231.9011.34
2023-06-16 11:31:20,891 [  16657] SEVERE - #c.i.o.a.i.FlushQueue - JDK: 17.0.6; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2023-06-16 11:31:20,892 [  16658] SEVERE - #c.i.o.a.i.FlushQueue - OS: Mac OS X
2023-06-16 11:31:20,893 [  16659] SEVERE - #c.i.o.a.i.FlushQueue - Plugin to blame: Atom Material Icons version: 91.0.0
```

</details>

Hope this helps

**Comment by Karbust** [comment]
I have the same issue with CLion...

``` 
Build #CL-231.9011.31, built on May 15, 2023
Licensed to REDACTED.
Runtime version: 17.0.6+10-b829.9 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

Operating System:
Edition - Windows 10 Pro
Version - 22H2
OS build - 19045.3086
```

WebStorm and Rider don't have this issue.

**Comment by Denia-park** [comment]
I have the same issue with IntelliJ Idea 2023.1.2 on startup

so i downgrade version 91.0 -> 90.0

**Comment by udaya28** [comment]
+1

**Comment by JohnnyDevNull** [comment]
Same with WebStorm, i've downgraded manually to 90.0.0

**Comment by mallowigi** [comment]
Thanks for the report, I've currently disabled the update until I figure out the issue. Please downgrade to 90 in the meantime.

The version is fixing a change in the api in the eap. But I forgot to change the minimal version and it affected the release versions. Sorry for that!
