### ISSUE TITLE
missing preview icons

### ISSUE THREAD

**Issue by Abdelraman** [mallowigi/a-file-icon-idea#406]
version 93.0.0 

file icons are not longer available, kindly check the attached screen short

![image](https://github.com/mallowigi/a-file-icon-idea/assets/4821833/c1e6d1c1-a63d-4fe8-9313-61280ada9010)

as well some php icons missing from the previous release

Thanks

**Comment by jdreesen** [comment]
I got this exception:

```
java.lang.RuntimeException: Cannot invoke (class=MyFileTypeListener, method=fileTypesChanged, topic=FileTypeListener)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:676)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:422)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:401)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:460)
	at jdk.proxy2/jdk.proxy2.$Proxy234.fileTypesChanged(Unknown Source)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.fireFileTypesChanged(FileTypeManagerImpl.java:1047)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.fireFileTypesChanged(FileTypeManagerImpl.java:1028)
	at com.mallowigi.icons.services.IconPatchersManager.updateFileIcons$lambda$2$lambda$0(IconPatchersManager.kt:60)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:992)
	at com.mallowigi.icons.services.IconPatchersManager.updateFileIcons$lambda$2(IconPatchersManager.kt:60)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:208)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:190)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:478)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:121)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:789)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:740)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:734)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:759)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:685)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithoutImplicitRead(ApplicationImpl.java:1485)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:992)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:992)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: com.intellij.openapi.extensions.SortingException: Could not satisfy sorting requirements: PhpFileIconProvider(first); null(before PhpFileIconProvider)
	at com.intellij.openapi.extensions.LoadingOrder$Companion.sort(LoadingOrder.kt:188)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getSortedAdapters(ExtensionPointImpl.java:394)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:410)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensionList(ExtensionPointImpl.java:248)
	at com.intellij.openapi.extensions.ExtensionPointName.getExtensionList(ExtensionPointName.kt:43)
	at com.intellij.util.IconUtil.getProviderIcon(IconUtil.kt:226)
	at com.intellij.util.IconUtil.computeFileIconImpl(IconUtil.kt:167)
	at com.intellij.util.IconUtil.computeFileIcon(IconUtil.kt:159)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.updateFileIcon(FileEditorManagerImpl.kt:578)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$MyFileTypeListener.fileTypesChanged(FileEditorManagerImpl.kt:1814)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:699)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:659)
	... 47 more
```

**Comment by mallowigi** [comment]
I sent a hotfix to the marketplace. In the meantime, you can download it here: https://plugins.jetbrains.com/plugin/10044-atom-material-icons/versions

**Comment by Abdelraman** [comment]
It seems sent link open the versions mentioning that the latest is 93.0,
waiting for the hot fix to be release by marketplace.

concerning the file icons, the previous version used to show specific icon for class 
![image](https://github.com/mallowigi/a-file-icon-idea/assets/4821833/52dd2c67-8a42-49e5-b1ba-1ff891eadd7e)
different from normal files icon
![image](https://github.com/mallowigi/a-file-icon-idea/assets/4821833/d231b643-95ed-44e0-ae8d-acf27a3cf8bb)
for the new version the classes as well as normal files e.g. (config files) has the same icons in the second screen shot,
I don't know if that is considered to be an issue.

**Comment by mallowigi** [comment]
<img width="2168" alt="CleanShot 2023-08-21 at 15 36 49@2x" src="https://github.com/mallowigi/a-file-icon-idea/assets/5015756/ad4c2b02-9f16-4f77-aca1-4dfb23a33918">
should be fixed in the upcoming release

**Comment by benstockdesign** [comment]
I, too, am having this problem. I clicked the hot fix link @mallowigi posted, and the page says the latest version is 93.0.0, which is the same version of the plugin I currently have installed. How long does it usually take for JetBrains to update the marketplace? I need my icons, man! They’re everything to me. 🥺

**Comment by mallowigi** [comment]
How come you're not seeing 93.0.1? 

And yeah I don't know what is their schedule for validating... if they still didn't approve by tomorrow I'll ping them directly

**Comment by jdreesen** [comment]
I don't see it either. Maybe because it's not approved yet?

**Comment by benstockdesign** [comment]
> How come you're not seeing 93.0.1?
> 
> And yeah I don't know what is their schedule for validating... if they still didn't approve by tomorrow I'll ping them directly

I just got the 93.0.1 update! I’m in the middle of the US and I’ve never been able to understand how time zones work (or leap seconds for that matter), so it probably just had something to do with timing or something. Who knows? Thanks for the quick update though! I appreciate it. You do good work!

**Comment by Abdelraman** [comment]
just received and installed the updates, I have got an error

![image](https://github.com/mallowigi/a-file-icon-idea/assets/4821833/c9043f2b-3213-4313-8632-184903711672)

java.lang.IllegalStateException: Unexpected element while parsing cmd 'c' encountered token '-1e-4.000183' rest=-1e-4.0001(index=264 in input=m16.56 5.9994c-.0046.000383-.0087.00127-.01324.00165-.42659.03629-.83051.09268-1.1813.19192-.55415.166-1.0532.40447-1.494.71803-.4282.32278-.81705.72086-1.1697 1.1912-.34004.47956-.6824 1.0323-1.0224 1.6594-.12109.22868-.23331.42505-.35074.63696v.0017c-1e-4.000183-.0032-.000183-.0033 0l-1.3401 2.394-.005-.0017c-.23782.4425-.46149.84702-.66509 1.1978-.2141.36889-.45189.6815-.71637.93972-.26448.25822-.56659.45561-.90663.59394-.071945.02731-.1614.04195-.24155.06287-.0005144.000134-.00114-.000134-.00165 0h-.9877v2.4138h.98935v-.0017c.42844-.03628.83244-.09229 1.1846-.19192.55415-.166 1.0532-.40447 1.494-.71803.4282-.32278.8187-.72086 1.1713-1.1912.34005-.47956.68074-1.0323 1.0208-1.6594.12084-.22819.23523-.42557.3524-.63696l.0066.0017.0033-.005.0364-.06618h2.5296v.0017h1.125v-2.4072h-.33089v-.0017h-1.9787c.21975-.40713.43079-.78837.62041-1.1151.2141-.36889.45189-.6815.71637-.93972.26448-.25822.56659-.45561.90663-.59394.07046-.026754.15931-.041111.23824-.061214h.99266v-.00331h-.0017v-2.4105h-.97777v-.00165z)
	at com.github.weisj.jsvg.au.e(SourceFile:127)
	at com.github.weisj.jsvg.au.f(SourceFile:238)
	at com.github.weisj.jsvg.df.a(SourceFile:38)
	at com.github.weisj.jsvg.aX.a(SourceFile:60)
	at com.github.weisj.jsvg.be.build(SourceFile:91)
	at com.github.weisj.jsvg.parser.ParsedElement.build(SourceFile:115)
	at com.github.weisj.jsvg.parser.ParsedElement.build(SourceFile:113)
	at com.github.weisj.jsvg.parser.ParsedElement.build(SourceFile:113)
	at com.intellij.ui.svg.JSvgDocumentFactoryKt.buildDocument(JSvgDocumentFactory.kt:109)
	at com.intellij.ui.svg.JSvgDocumentFactoryKt.createJSvgDocument(JSvgDocumentFactory.kt:36)
	at com.intellij.ui.svg.SvgKt.renderImage(svg.kt:294)
	at com.intellij.ui.svg.SvgKt.renderAndCache-rdQnj48(svg.kt:261)
	at com.intellij.ui.svg.SvgKt.access$renderAndCache-rdQnj48(svg.kt:1)
	at com.intellij.ui.svg.SvgKt.loadSvgAndCacheIfApplicable-F6nGey4(svg.kt:590)
	at com.intellij.ui.icons.ImageCacheKt.doLoadByDescriptor(imageCache.kt:290)
	at com.intellij.ui.icons.ImageCacheKt.loadByDescriptorWithoutCache(imageCache.kt:177)
	at com.intellij.ui.icons.ImageCacheKt.loadImage(imageCache.kt:139)
	at com.intellij.ui.icons.ImageDataByPathResourceLoader.loadImage(ImageDataByUrlLoader.kt:65)
	at com.intellij.ui.icons.CachedImageIcon.loadImage$intellij_platform_util_ui(CachedImageIcon.kt:313)
	at com.intellij.ui.icons.ScaledIconCache.getOrScaleIcon(ScaledIconCache.kt:43)
	at com.intellij.ui.icons.CachedImageIcon.resolveActualIcon(CachedImageIcon.kt:158)
	at com.intellij.ui.icons.CachedImageIcon.getIconHeight(CachedImageIcon.kt:121)
	at icons.AtomIcons.loadIconWithFallback(AtomIcons.kt:118)
	at com.mallowigi.icons.providers.DefaultFileIconProvider.getIcon(DefaultFileIconProvider.kt:41)
	at com.mallowigi.icons.providers.AbstractFileIconProvider.loadIcon(AbstractFileIconProvider.kt:83)
	at com.mallowigi.icons.providers.AbstractFileIconProvider.access$loadIcon(AbstractFileIconProvider.kt:40)
	at com.mallowigi.icons.providers.AbstractFileIconProvider$getIconForAssociation$1.invoke(AbstractFileIconProvider.kt:75)
	at com.mallowigi.icons.providers.AbstractFileIconProvider$getIconForAssociation$1.invoke(AbstractFileIconProvider.kt:75)
	at com.mallowigi.icons.providers.AbstractFileIconProvider.getIconForAssociation$lambda$0(AbstractFileIconProvider.kt:75)
	at java.base/java.util.Optional.map(Optional.java:260)
	at com.mallowigi.icons.providers.AbstractFileIconProvider.getIconForAssociation(AbstractFileIconProvider.kt:75)
	at com.mallowigi.icons.providers.AbstractFileIconProvider.findIcon(AbstractFileIconProvider.kt:67)
	at com.mallowigi.icons.providers.AbstractFileIconProvider.getIcon(AbstractFileIconProvider.kt:50)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:21)
	at com.intellij.psi.impl.ElementBase.doComputeIconNow(ElementBase.java:98)
	at com.intellij.psi.impl.ElementBase.lambda$computeIconNow$3(ElementBase.java:94)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:130)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:119)
	at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:94)
	at com.intellij.psi.impl.ElementBase.lambda$static$0(ElementBase.java:45)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.kt:279)
	at com.intellij.ui.DeferredIconImpl$scheduleCalculationIfNeeded$1$result$1$1.invoke(DeferredIconImpl.kt:218)
	at com.intellij.ui.DeferredIconImpl$scheduleCalculationIfNeeded$1$result$1$1.invoke(DeferredIconImpl.kt:218)
	at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:105)
	at com.intellij.openapi.application.rw.InternalReadAction.access$insideReadAction(InternalReadAction.kt:14)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$2.invoke(InternalReadAction.kt:95)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$2.invoke(InternalReadAction.kt:94)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke$lambda$1$lambda$0(cancellableReadAction.kt:41)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1133)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke$lambda$1(cancellableReadAction.kt:39)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:133)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke(cancellableReadAction.kt:37)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:248)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal(cancellableReadAction.kt:34)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable(InternalReadAction.kt:94)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadAction(InternalReadAction.kt:76)
	at com.intellij.openapi.application.rw.InternalReadAction.readLoop(InternalReadAction.kt:63)
	at com.intellij.openapi.application.rw.InternalReadAction.access$readLoop(InternalReadAction.kt:14)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invokeSuspend(InternalReadAction.kt:42)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invoke(InternalReadAction.kt)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invoke(InternalReadAction.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.openapi.application.rw.InternalReadAction.runReadAction(InternalReadAction.kt:38)
	at com.intellij.openapi.application.rw.PlatformReadWriteActionSupport.executeReadAction(PlatformReadWriteActionSupport.kt:38)
	at com.intellij.openapi.application.ReadWriteActionSupport.executeReadAction$default(ReadWriteActionSupport.kt:15)
	at com.intellij.openapi.application.CoroutinesKt.constrainedReadAction(coroutines.kt:58)
	at com.intellij.openapi.application.CoroutinesKt.readAction(coroutines.kt:25)
	at com.intellij.ui.DeferredIconImpl$scheduleCalculationIfNeeded$1$invokeSuspend$$inlined$evaluateDeferred$1.invokeSuspend(IconDeferrerImpl.kt:91)
	at com.intellij.ui.DeferredIconImpl$scheduleCalculationIfNeeded$1$invokeSuspend$$inlined$evaluateDeferred$1.invoke(IconDeferrerImpl.kt)
	at com.intellij.ui.DeferredIconImpl$scheduleCalculationIfNeeded$1$invokeSuspend$$inlined$evaluateDeferred$1.invoke(IconDeferrerImpl.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.ui.DeferredIconImpl$scheduleCalculationIfNeeded$1.invokeSuspend(DeferredIconImpl.kt:374)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.lang.NumberFormatException: For input string: "-1e-4.000183"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
	at java.base/jdk.internal.math.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
	at java.base/java.lang.Float.parseFloat(Float.java:476)
	at com.github.weisj.jsvg.au.e(SourceFile:121)
	... 82 more

**Comment by mallowigi** [comment]
Irrelevant to this issue, you already opened an issue about it, and apparently this fix doesn't fix your issue.
