### ISSUE TITLE
[Bug]: Control-flow exceptions should never be logged

### ISSUE THREAD

**Issue by mgroth0** [mallowigi/a-file-icon-idea#415]
```
java.lang.Throwable: Control-flow exceptions (e.g. this class com.intellij.openapi.progress.ProcessCanceledException) should never be logged. Instead, these should have been rethrown if caught.
	at com.intellij.openapi.diagnostic.Logger.ensureNotControlFlow(Logger.java:513)
	at com.intellij.idea.IdeaLogger.doLogError(IdeaLogger.java:154)
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:145)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:436)
	at com.mallowigi.icons.providers.AbstractFileIconProvider.loadIcon(AbstractFileIconProvider.kt:85)
	at com.mallowigi.icons.providers.AbstractFileIconProvider.access$loadIcon(AbstractFileIconProvider.kt:40)
	at com.mallowigi.icons.providers.AbstractFileIconProvider$getIconForAssociation$1.invoke(AbstractFileIconProvider.kt:75)
	at com.mallowigi.icons.providers.AbstractFileIconProvider$getIconForAssociation$1.invoke(AbstractFileIconProvider.kt:75)
	at com.mallowigi.icons.providers.AbstractFileIconProvider.getIconForAssociation$lambda$0(AbstractFileIconProvider.kt:75)
	at java.base/java.util.Optional.map(Optional.java:260)
	at com.mallowigi.icons.providers.AbstractFileIconProvider.getIconForAssociation(AbstractFileIconProvider.kt:75)
	at com.mallowigi.icons.providers.AbstractFileIconProvider.findIcon(AbstractFileIconProvider.kt:67)
	at com.mallowigi.icons.providers.AbstractFileIconProvider.getIcon(AbstractFileIconProvider.kt:50)
	at com.intellij.ide.projectView.impl.CompoundIconProvider.getIcon(CompoundIconProvider.java:29)
	at com.intellij.ide.projectView.impl.CompoundIconProvider.findIcon(CompoundIconProvider.java:52)
	at com.intellij.ide.projectView.impl.nodes.PsiDirectoryNode.setupIcon(PsiDirectoryNode.java:184)
	at com.intellij.ide.projectView.impl.nodes.PsiDirectoryNode.updateImpl(PsiDirectoryNode.java:124)
	at org.jetbrains.plugins.gradle.projectView.GradleTreeStructureProvider$GradleModuleDirectoryNode.updateImpl(GradleTreeStructureProvider.java:253)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.lambda$doUpdate$1(AbstractPsiBasedNode.java:207)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:879)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.doUpdate(AbstractPsiBasedNode.java:160)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.lambda$update$0(AbstractPsiBasedNode.java:156)
	at com.intellij.util.AstLoadingFilter.lambda$toComputable$2(AstLoadingFilter.java:171)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:129)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:118)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:108)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.update(AbstractPsiBasedNode.java:156)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.getUpdatedPresentation(PresentableNodeDescriptor.java:88)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.update(PresentableNodeDescriptor.java:32)
	at com.intellij.ui.tree.StructureTreeModel$Node.update(StructureTreeModel.java:486)
	at com.intellij.ui.tree.StructureTreeModel$Node.<init>(StructureTreeModel.java:467)
	at com.intellij.ui.tree.StructureTreeModel$Node.<init>(StructureTreeModel.java:460)
	at com.intellij.ui.tree.StructureTreeModel.getValidChildren(StructureTreeModel.java:418)
	at com.intellij.ui.tree.StructureTreeModel.validateChildren(StructureTreeModel.java:329)
	at com.intellij.ui.tree.StructureTreeModel.getNode(StructureTreeModel.java:323)
	at com.intellij.ui.tree.StructureTreeModel.getChildren(StructureTreeModel.java:343)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.getNode(AsyncTreeModel.java:615)
	at com.intellij.ui.tree.AsyncTreeModel$Command.get(AsyncTreeModel.java:490)
	at com.intellij.ui.tree.AsyncTreeModel$Command.get(AsyncTreeModel.java:433)
	at com.intellij.util.concurrency.Invoker$Task.run(Invoker.java:381)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1076)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:76)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:133)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:114)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:76)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:73)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:111)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:76)
	at com.intellij.util.concurrency.Invoker.startTask(Invoker.java:238)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:194)
	at com.intellij.util.concurrency.Invoker.lambda$offerSafely$0(Invoker.java:177)
	at com.intellij.util.concurrency.Invoker$Background.lambda$offer$0(Invoker.java:508)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:244)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:30)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:222)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:210)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.intellij.openapi.progress.ProcessCanceledException
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.throwIfCanceled(AbstractProgressIndicatorBase.java:158)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.checkCanceled(AbstractProgressIndicatorBase.java:148)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorExBase.checkCanceled(AbstractProgressIndicatorExBase.java:89)
	at com.intellij.openapi.progress.impl.CoreProgressManager.doCheckCanceled(CoreProgressManager.java:143)
	at com.intellij.openapi.progress.ProgressManager.checkCanceled(ProgressManager.java:233)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$IdeIOCancellationCallback.checkCancelled(ProgressManagerImpl.java:241)
	at com.intellij.util.io.IOCancellationCallbackHolder.checkCancelled(IOCancellationCallbackHolder.kt:23)
	at com.intellij.util.io.PersistentHashMapValueStorage.checkCancellation(PersistentHashMapValueStorage.java:688)
	at com.intellij.util.io.PersistentHashMapValueStorage.readBytes(PersistentHashMapValueStorage.java:567)
	at com.intellij.util.io.PersistentMapImpl.doGet(PersistentMapImpl.java:671)
	at com.intellij.util.io.PersistentMapImpl.get(PersistentMapImpl.java:607)
	at com.intellij.util.io.PersistentHashMap.get(PersistentHashMap.java:195)
	at com.intellij.ui.svg.SvgCacheManager.loadFromCache(SvgCacheManager.kt:172)
	at com.intellij.ui.svg.SvgKt.loadSvgAndCacheIfApplicable-F6nGey4(svg.kt:542)
	at com.intellij.ui.icons.ImageCacheKt.doLoadByDescriptor(imageCache.kt:267)
	at com.intellij.ui.icons.ImageCacheKt.loadByDescriptorWithoutCache(imageCache.kt:154)
	at com.intellij.ui.icons.ImageCacheKt.loadImage(imageCache.kt:116)
	at com.intellij.ui.icons.ImageDataByPathResourceLoader.loadImage(ImageDataByUrlLoader.kt:65)
	at com.intellij.ui.icons.CachedImageIcon.loadImage$intellij_platform_util_ui(CachedImageIcon.kt:324)
	at com.intellij.ui.icons.ScaledIconCache.loadIcon(ScaledIconCache.kt:71)
	at com.intellij.ui.icons.ScaledIconCache.getOrScaleIcon(ScaledIconCache.kt:66)
	at com.intellij.ui.icons.CachedImageIcon.resolveActualIcon(CachedImageIcon.kt:155)
	at com.intellij.ui.icons.CachedImageIcon.getIconHeight(CachedImageIcon.kt:118)
	at com.mallowigi.icons.special.DirIcon.getIconHeight(DirIcon.kt:49)
	at icons.AtomIcons.loadIconWithFallback(AtomIcons.kt:118)
	at com.mallowigi.icons.providers.DefaultFolderIconProvider.getIcon(DefaultFolderIconProvider.kt:41)
	at com.mallowigi.icons.providers.AbstractFileIconProvider.loadIcon(AbstractFileIconProvider.kt:83)
	... 67 more
```

Atom Material Icons 94.0.0

```
IntelliJ IDEA 2023.3 EAP (Ultimate Edition)
Build #IU-233.6745.305, built on September 21, 2023
Licensed to IntelliJ IDEA EAP user: Matthew Groth
Expiration date: October 21, 2023
Runtime version: 17.0.8.1+7-b1059.3 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.0
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 10
Metal Rendering is ON
Registry:
  editor.focus.mode.color.light=323232
  editor.paint.empty.text=false
  debugger.new.tool.window.layout=true
  ide.animate.toolwindows=true
  ide.plugins.snapshot.on.unload.fail=true
  search.everywhere.settings=true
  ide.slow.operations.assertion=false
  ide.new.editor.tabs.vertical.borders=true
  ide.experimental.ui=true
  ide.balloon.shadow.size=0
  editor.focus.mode.color.dark=323232
Non-Bundled Plugins:
  Shifter (1.9.6)
  jclasslib (6.0.4.2)
  YourKit Java Profiler 2023.9-b96 Integration (2023.9.96.0)
  de.kontext_e.idea.plugins.autofill (1.2)
  au.com.glassechidna.luanalysis (1.4.0)
  krasa.CpuUsageIndicator (1.17.2023)
  org.jetbrains.plugins.rest (233.6745.297)
  com.github.camork.fileExpander (2.2)
  com.pinkfloyded.idea-file-path-autocomplete.idea-file-path-autocomplete (0.4.1)
  com.mallowigi (94.0.0)
  JProfiler (19.9.3)
  org.jetbrains.compose.desktop.ide (1.5.2)
  com.suusan2go.kotlin-fill-class (1.0.22)
  androidx.compose.plugins.idea (233.6745.305)
  Pythonid (233.6745.305)
  org.exbin.deltahex.intellij (0.2.8.1)
  com.chrisrm.idea.MaterialThemeUI (8.12.2)
  org.mallowigi.idea.MaterialThemeUI.LangAdditions (2024.1.1)
  org.mallowigi.idea.MaterialThemeUI.HighContrast (2024.1.1)
  org.mallowigi.idea.MaterialThemeUI.Extras (2024.1.1)
  org.mallowigi.idea.MaterialThemeUI.ProjectFrame (2024.1.1)
  org.mallowigi.idea.MaterialThemeUI.CustomTheme (2024.1.1)
  com.clutcher.comments_highlighter (2023.7.12)
  matt.idea.ide-open-1 (1.0)
  com.mnw.tabmover (1.5.2)
Kotlin: 233-1.9.0-release-358-IJ6745.305
```

**Comment by mallowigi** [comment]
I'm seeing that as well, but I can't seem to reproduce on the sandbox... 

I tried removing the logger, let's see what happens
