### ISSUE TITLE
Latest 94.1.0 update is full of errors when used with 2023.3

### ISSUE THREAD

**Issue by danwilliams** [mallowigi/a-file-icon-idea#419]
### Describe the bug
I just updated the plugin from 94.0.0 to 94.1.0, which according to the changelog was meant to fix an error with filtering. However, this latest plugin version is _totally_ broken. 

### To Reproduce
1. Use the plugin with RustRover 2023.3
2. You will see a whole list of errors (I get 40-70 just starting up) and none of the icons will appear

### Expected Behavior
No errors and the icons should appear :slightly_smiling_face: 

### Environment
  - Ubuntu 23.04
  - RustRover 2023.3 EAP
  - Atom Material Icons 94.1.0

```
RustRover 2023.3 EAP
Build #RR-233.8264.22, built on October 10, 2023
Licensed to RustRover EAP user: Dan Williams
Expiration date: December 9, 2023
Runtime version: 17.0.8.1+7-b1063.1 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.2.0-34-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 16384M
Cores: 16
Non-Bundled Plugins:
  com.markskelton.one-dark-theme (5.9.0)
  atom-one (1.5.1)
  com.mallowigi (94.1.0)
Current Desktop: ubuntu:GNOME
```

### Screenshots
![image](https://github.com/mallowigi/a-file-icon-idea/assets/365912/48f92618-02a4-4d10-8173-84b6bf9ce182)

### Errors
There are many variations on the examples below:
<details><summary>Example error 1</summary>

```
java.lang.AbstractMethodError: Receiver class com.mallowigi.icons.svgpatchers.MainSvgPatcher$createPatcher$1 does not define or inherit an implementation of the resolved method 'abstract long[] digest()' of interface com.intellij.ui.svg.SvgAttributePatcher.
	at com.intellij.ui.svg.SvgKt.loadSvgFromClassResource-NPNtGws(svg.kt:442)
	at com.intellij.ui.svg.SvgKt.loadSvgFromClassResource-NPNtGws$default(svg.kt:64)
	at com.intellij.ui.icons.RasterizedImageDataLoaderKt.loadPatched(RasterizedImageDataLoader.kt:248)
	at com.intellij.ui.icons.RasterizedImageDataLoaderKt.loadRasterized(RasterizedImageDataLoader.kt:163)
	at com.intellij.ui.icons.RasterizedImageDataLoaderKt.access$loadRasterized(RasterizedImageDataLoader.kt:1)
	at com.intellij.ui.icons.RasterizedImageDataLoader.loadImage(RasterizedImageDataLoader.kt:75)
	at com.intellij.ui.icons.CachedImageIcon.loadImage$intellij_platform_util_ui(CachedImageIcon.kt:327)
	at com.intellij.ui.icons.ScaledIconCache.loadIcon(ScaledIconCache.kt:71)
	at com.intellij.ui.icons.ScaledIconCache.getOrScaleIcon(ScaledIconCache.kt:66)
	at com.intellij.ui.icons.CachedImageIcon.resolveActualIcon(CachedImageIcon.kt:158)
	at com.intellij.ui.icons.CachedImageIcon.getIconWidth(CachedImageIcon.kt:119)
	at com.intellij.openapi.util.IconLoader.isGoodSize(IconLoader.kt:239)
	at com.intellij.openapi.actionSystem.impl.ActionButton.updateIcon(ActionButton.java:419)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateAllToolbarsImmediately(ActionToolbarImpl.java:121)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateAllToolbarsImmediately(ActionToolbarImpl.java:110)
	at com.mallowigi.utils.UiUtilsKt.replaceArrowIcons$lambda$0(UiUtils.kt:93)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:687)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:588)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:44)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:588)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:71)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:353)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:793)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:353)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1006)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1006)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:348)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:851)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:390)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```
</details>
<details><summary>Example error 2</summary>
```
java.lang.AbstractMethodError: Method com/mallowigi/icons/svgpatchers/MainSvgPatcher$createPatcher$1.digest()[J is abstract
	at com.mallowigi.icons.svgpatchers.MainSvgPatcher$createPatcher$1.digest(MainSvgPatcher.kt)
	at com.intellij.ui.svg.SvgKt.loadSvgFromClassResource-NPNtGws(svg.kt:442)
	at com.intellij.ui.svg.SvgKt.loadSvgFromClassResource-NPNtGws$default(svg.kt:64)
	at com.intellij.ui.icons.RasterizedImageDataLoaderKt.loadPatched(RasterizedImageDataLoader.kt:248)
	at com.intellij.ui.icons.RasterizedImageDataLoaderKt.loadRasterized(RasterizedImageDataLoader.kt:163)
	at com.intellij.ui.icons.RasterizedImageDataLoaderKt.access$loadRasterized(RasterizedImageDataLoader.kt:1)
	at com.intellij.ui.icons.RasterizedImageDataLoader.loadImage(RasterizedImageDataLoader.kt:75)
	at com.intellij.ui.icons.CachedImageIcon.loadImage$intellij_platform_util_ui(CachedImageIcon.kt:327)
	at com.intellij.ui.icons.ScaledIconCache.loadIcon(ScaledIconCache.kt:71)
	at com.intellij.ui.icons.ScaledIconCache.getOrScaleIcon(ScaledIconCache.kt:66)
	at com.intellij.ui.icons.CachedImageIcon.resolveActualIcon(CachedImageIcon.kt:158)
	at com.intellij.ui.icons.CachedImageIcon.getIconWidth(CachedImageIcon.kt:119)
	at com.intellij.ui.RowIcon.updateSize(RowIcon.kt:142)
	at com.intellij.ui.RowIcon.getIconHeight(RowIcon.kt:127)
	at com.intellij.ui.DeferredIconImpl.getIconHeight(DeferredIconImpl.kt:314)
	at com.intellij.util.IconUtil.cropIcon(IconUtil.kt:88)
	at com.intellij.ide.navbar.impl.PsiNavBarItem.getIcon(DefaultNavBarItem.kt:152)
	at com.intellij.ide.navbar.impl.DefaultNavBarItem.presentation(DefaultNavBarItem.kt:53)
	at com.intellij.ide.navbar.ide.IdeNavBarVmItem.<init>(IdeNavBarVmItem.kt:24)
	at com.intellij.ide.navbar.ide.IdeNavBarVmItemKt.toVmItems(IdeNavBarVmItem.kt:74)
	at com.intellij.ide.navbar.ide.NavBarServiceKt.contextModelInner(NavBarService.kt:166)
	at com.intellij.ide.navbar.ide.NavBarServiceKt.access$contextModelInner(NavBarService.kt:1)
	at com.intellij.ide.navbar.ide.NavBarServiceKt$contextModel$2.invoke(NavBarService.kt:144)
	at com.intellij.ide.navbar.ide.NavBarServiceKt$contextModel$2.invoke(NavBarService.kt:143)
	at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:108)
	at com.intellij.openapi.application.rw.InternalReadAction.access$insideReadAction(InternalReadAction.kt:16)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$2.invoke(InternalReadAction.kt:95)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$2.invoke(InternalReadAction.kt:94)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke$lambda$1$lambda$0(cancellableReadAction.kt:38)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke$lambda$1(cancellableReadAction.kt:36)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:73)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:128)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke(cancellableReadAction.kt:34)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContextInner(coroutines.kt:324)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:313)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal(cancellableReadAction.kt:31)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable(InternalReadAction.kt:94)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadAction(InternalReadAction.kt:78)
	at com.intellij.openapi.application.rw.InternalReadAction.readLoop(InternalReadAction.kt:65)
	at com.intellij.openapi.application.rw.InternalReadAction.access$readLoop(InternalReadAction.kt:16)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invokeSuspend(InternalReadAction.kt:44)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```
</details>
<details><summary>Example error 3</summary>
```
java.io.FileNotFoundException: /icons/files/testrustfiles.svg (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
	at icons.AtomIcons.loadSVGIcon(AtomIcons.kt:107)
	at icons.AtomIcons.loadIconWithFallback(AtomIcons.kt:118)
	at com.mallowigi.icons.providers.DefaultFileIconProvider.getIcon(DefaultFileIconProvider.kt:41)
	at com.mallowigi.icons.providers.AbstractFileIconProvider.loadIcon(AbstractFileIconProvider.kt:82)
	at com.mallowigi.icons.providers.AbstractFileIconProvider.access$loadIcon(AbstractFileIconProvider.kt:40)
	at com.mallowigi.icons.providers.AbstractFileIconProvider$getIconForAssociation$1.invoke(AbstractFileIconProvider.kt:75)
	at com.mallowigi.icons.providers.AbstractFileIconProvider$getIconForAssociation$1.invoke(AbstractFileIconProvider.kt:75)
	at com.mallowigi.icons.providers.AbstractFileIconProvider.getIconForAssociation$lambda$0(AbstractFileIconProvider.kt:75)
	at java.base/java.util.Optional.map(Optional.java:260)
	at com.mallowigi.icons.providers.AbstractFileIconProvider.getIconForAssociation(AbstractFileIconProvider.kt:75)
	at com.mallowigi.icons.providers.AbstractFileIconProvider.findIcon(AbstractFileIconProvider.kt:67)
	at com.mallowigi.icons.providers.AbstractFileIconProvider.getIcon(AbstractFileIconProvider.kt:50)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.kt:20)
	at com.intellij.ide.FileIconPatcherImpl.getIcon(FileIconPatcherImpl.java:22)
	at com.intellij.util.IconUtil.getProviderIcon(IconUtil.kt:227)
	at com.intellij.util.IconUtil.computeFileIconImpl(IconUtil.kt:167)
	at com.intellij.util.IconUtil.computeFileIcon(IconUtil.kt:158)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters$doUpdateFileIcon$icon$1.invoke(EditorsSplitters.kt:399)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters$doUpdateFileIcon$icon$1.invoke(EditorsSplitters.kt:398)
	at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:108)
	at com.intellij.openapi.application.rw.InternalReadAction.access$insideReadAction(InternalReadAction.kt:16)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$2.invoke(InternalReadAction.kt:95)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$2.invoke(InternalReadAction.kt:94)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke$lambda$1$lambda$0(cancellableReadAction.kt:38)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke$lambda$1(cancellableReadAction.kt:36)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:73)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:128)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke(cancellableReadAction.kt:34)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContextInner(coroutines.kt:324)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:313)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal(cancellableReadAction.kt:31)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable(InternalReadAction.kt:94)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadAction(InternalReadAction.kt:78)
	at com.intellij.openapi.application.rw.InternalReadAction.readLoop(InternalReadAction.kt:65)
	at com.intellij.openapi.application.rw.InternalReadAction.access$readLoop(InternalReadAction.kt:16)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invokeSuspend(InternalReadAction.kt:44)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invoke(InternalReadAction.kt)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invoke(InternalReadAction.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.openapi.application.rw.InternalReadAction.runReadAction(InternalReadAction.kt:40)
	at com.intellij.openapi.application.rw.PlatformReadWriteActionSupport.executeReadAction(PlatformReadWriteActionSupport.kt:38)
	at com.intellij.openapi.application.ReadWriteActionSupport.executeReadAction$default(ReadWriteActionSupport.kt:15)
	at com.intellij.openapi.application.CoroutinesKt.constrainedReadAction(coroutines.kt:58)
	at com.intellij.openapi.application.CoroutinesKt.readAction(coroutines.kt:25)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters.doUpdateFileIcon$intellij_platform_ide_impl(EditorsSplitters.kt:398)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters$iconUpdateChannel$1.invokeSuspend(EditorsSplitters.kt:138)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```
</details>

**Comment by mallowigi** [comment]
My mistake. The last version is for the latest EAP build and moving. I changed the minimum version right now, please revert back to 94.0

**Comment by danwilliams** [comment]
@mallowigi I think you should issue a new update to correct this...? I won't be the only person upgrading to the broken version?

**Comment by CrazyBoy49z** [comment]
> My mistake. The last version is for the latest EAP build and moving (233.9802). I changed the minimum version right now, please revert back to 94.0

In marketplace 94.1.0
<img width="725" alt="image" src="https://github.com/mallowigi/a-file-icon-idea/assets/3448603/b97685b8-6cd2-4b97-9f48-9cc1c5e5cbf4">

**Comment by CrazyBoy49z** [comment]
Yes 

```
PhpStorm 2023.3 EAP
Build #PS-233.9802.11, built on October 12, 2023
Licensed to PhpStorm EAP user: Yurij Finiv
Expiration date: November 11, 2023
Runtime version: 17.0.8.1+7-b1072.1 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.7
GC: G1 Young Generation, G1 Old Generation
Memory: 4048M
Cores: 8
Metal Rendering is ON
Registry:
  debugger.new.tool.window.layout=true
  ide.windowSystem.autoShowProcessPopup=true
  run.processes.with.pty=TRUE
  ide.experimental.ui=true
  ide.balloon.shadow.size=0
  ide.images.show.chessboard=true
Non-Bundled Plugins:
  com.github.czy211.licensetemplate (2.0.0)
  LiveTemplatePreview (0.3)
  com.fwdekker.randomness (2.7.7)
  club.nutsoft.Github3Theme (1.2.0)
  com.intellij.javafx (1.0.4)
  com.intellij.plugins.mnemonicKeymap (2023.1.0)
  com.rmondjone.jsontotypescript (2023.1.2)
  cc.moky.intellij.plugin.svga-support (1.0.9)
  io.aesy.regex101 (0.2)
  com.jetbrains.edu (2023.9-2023.2-696)
  com.github.warningimhack3r.npmupdatedependencies (2.0.0)
  com.github.copilot (1.3.2.3528-nightly)
  com.github.catppuccin.jetbrains (3.0.0)
  com.materkey.codepoints (1.0.2)
  com.mroche.JsonHelper (1.3.0)
  org.OverEngineer.InlineProblems (0.5.0)
  com.godwin.json.parser (1.7)
  lermitage.intellij.iconviewer (1.22.4)
  com.wix.scss.lint (2.1.1)
  com.jetbrains.naming-is-hard (1.4.0)
  com.wix.sasslint (1.1.2)
  bundled-phpstorm-help (233.9102.195)
  String Manipulation (9.11.3)
  dev.meanmail.plugin.nginx-intellij-plugin (2022.1.1)
  krasa.CpuUsageIndicator (1.18.0-IJ2023)
  intellij-clock (2.0.0)
  com.xtu.plugins.reviewer (1.1.3)
  indent-rainbow.indent-rainbow (2.2.0)
  com.wakatime.intellij.plugin (14.2.3)
  com.khande.idea.plugin.TabNumberIndicator (1.0)
  ski.chrzanow.foldableprojectview (2.0.0-EAP.1)
  lermitage.intellij.battery.status (2.0)
  com.intellij.ml.llm (233.9802.14)
  org.jetbrains.plugins.astro (233.9802.6)
  com.kalessil.phpStorm.phpInspectionsEA (5.0.0.0)
  com.funivan.idea.phpClean (2023.04.01)
  ru.adelf.idea.dotenv (2023.3)
  de.espend.idea.php.annotation (9.4.0)
  net.rentalhost.plugins.php.hammer (0.26.0)
  dev.nybroe.collector (0.4.0)
  com.pestphp.pest-intellij (1.11.0)
  izhangzhihao.rainbow.brackets.lite (1.1.0)
  fr.adrienbrault.idea.symfony2plugin (2022.1.259)
  com.jetbrains.plugins.jslint (202.3)
  com.clutcher.comments_highlighter (2023.7.14)
  spy-js (233.9802.6)
  com.github.inxilpro.intellijalpine (v0.4.2)
  cn.yiiguxing.plugin.translate (3.5.5)
  org.i18nally.jetbrainsideplugin (1.4.2.1)
  com.mallowigi.colorHighlighter (17.1.0)
  com.laravel_idea.plugin (7.4.3.233)
  com.github.dinbtechit.vscodetheme (1.10.6)
  com.urswolfer.intellij.plugin.gerrit (1.2.6-203)
  com.mallowigi (94.1.0)
  zielu.gittoolbox (500.0.21+222)
  mobi.hsz.idea.gitignore (4.5.2)

```

**Comment by CrazyBoy49z** [comment]
But now not crush icon

**Comment by CrazyBoy49z** [comment]
<img width="407" alt="image" src="https://github.com/mallowigi/a-file-icon-idea/assets/3448603/61ed88d6-5b61-400f-ab7e-9b7be3c53b2e">

@danwilliams Build #PS-233.9802.11 work correctly
