### ISSUE TITLE
Parameter specified as non-null is null

### ISSUE THREAD

**Issue by apierri** [mallowigi/a-file-icon-idea#89]
Hi! First of all, great work on this plugin.

I'm having the following error _consistently_ on IntelliJ Idea 2020.1 . It started with the latest update.

java.lang.IllegalArgumentException: Parameter specified as non-null is null: method com.mallowigi.icons.special.DirIcon.paintIcon, parameter c
	at com.mallowigi.icons.special.DirIcon.paintIcon(DirIcon.kt)
	at com.intellij.ui.RowIcon.paintIcon(RowIcon.java:160)
	at com.intellij.openapi.util.IconLoader.toImage(IconLoader.java:374)
	at com.intellij.util.IconUtil.toImage(IconUtil.java:220)
	at com.intellij.util.IconUtil.toImage(IconUtil.java:216)
	at com.intellij.util.IconUtil.cropIcon(IconUtil.java:66)
	at com.intellij.ide.navigationToolbar.NavBarPresentation.getIcon(NavBarPresentation.java:66)
	at com.intellij.ide.navigationToolbar.NavBarItem.<init>(NavBarItem.java:58)
	at com.intellij.ide.navigationToolbar.NavBarItem.<init>(NavBarItem.java:45)
	at com.intellij.ide.navigationToolbar.NavBarUpdateQueue.rebuildUi(NavBarUpdateQueue.java:177)
	at com.intellij.ide.navigationToolbar.NavBarUpdateQueue$2.after(NavBarUpdateQueue.java:165)
	at com.intellij.ide.navigationToolbar.NavBarUpdateQueue$AfterModelUpdate.run(NavBarUpdateQueue.java:273)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:333)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:323)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:273)
	at com.intellij.util.ui.EdtInvocationManager.invokeAndWaitIfNeeded(EdtInvocationManager.java:64)
	at com.intellij.util.ui.UIUtil.invokeAndWaitIfNeeded(UIUtil.java:2339)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:284)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:242)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:232)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:367)
	at com.intellij.util.Alarm$Request.run(Alarm.java:357)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:220)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:310)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:741)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by mallowigi** [comment]
Looks like it is trying to find a folder icon but didnt' manage. Do you have a project i can test to ?

**Comment by apierri** [comment]
> Looks like it is trying to find a folder icon but didnt' manage. Do you have a project i can test to ?
Agh, sadly I can't provide you what you're asking. But I'll try to bring more information that might shed a light.

**Comment by mallowigi** [comment]
maybe just a screenshot of your project view?

**Comment by apierri** [comment]
Again, sorry, can't disclose that information as per NDA signed with my employer. I got a feeling I got you with your hands tied with this little information. 

> Looks like it is trying to find a folder icon but didnt' manage.

Maybe it has something to do with soft-links?

I'll try to debug the plugin today, maybe I can help.

**Comment by apierri** [comment]
Seems it's a type problem. Maybe `Component` type should actually be `Component?` type? The line that's calling you with a null component is here:
https://github.com/JetBrains/intellij-community/blob/82fd568e26deb15983b63ec369fa37e0b257eaf5/platform/util/ui/src/com/intellij/openapi/util/IconLoader.java#L375

And a non-nullable `Component` type is described here:

https://github.com/mallowigi/a-file-icon-idea/blob/fc38c528c28da7ed5e2ac90c78b1b900591fecaa/src/main/java/com/mallowigi/icons/special/DirIcon.kt#L36

That's my two cents. I hope it helps.
Thanks again for this awesome plugin.

**Comment by apierri** [comment]
This is solved in IntelliJ Idea **2020.2**, thanks!
